import { useEffect, useRef, useState, type ChangeEvent } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'

type Page = 'discover' | 'design' | 'workshop' | 'factory' | 'my' | 'detail' | 'designer'
type Corner = 'tl' | 'tr' | 'bl' | 'br'
type ArchiveFilter = 'all' | 'studio' | 'community'
type WorkshopMessage = {
  id: number
  type: 'ai' | 'user'
  sender: string
  text: string
}
type FactoryCam = {
  id: string
  label: string
  info: string
  feedText: string
}
type FactoryStep = {
  key: string
  title: string
  text: string
  state: 'done' | 'active' | 'pending'
}
type AuthTab = 'login' | 'register'
type MyOrder = {
  name: string
  id: string
  status: string
  statusType: 'prod' | 'done'
  eta: string
  muted?: boolean
}
type MyMatrixCard = {
  name: string
  status: string
  statusType: 'public' | 'reviewing'
  renderCode: string
  cloned: string
  likes: string
  yield: string
}
type SpotlightCard = {
  key: string
  className: string
  title: string
  center: string
  tag: string
  corners: Corner[]
}
type DesignerProfile = {
  id: string
  displayName: string
  node: string
  title: string
  streamNote: string
}
type DesignerAsset = {
  title: string
  engine: string
  image: string
}
type DesignerSection = {
  id: string
  pattern: 'split' | 'triple' | 'hero'
  assets: DesignerAsset[]
  serial: number
}

const discoverProjects = [
  {
    id: '01',
    name: 'Aero\nStrata',
    designer: 'Designed by K. YAMAMOTO',
    desc: '基于拓扑优化的极简流体力学骨架，去除冗余结构，整体重量削减 34%。纯粹由算法驱动的物理美学。',
    stamp: '[ FOOTWEAR_RENDER_01 ]',
    image:
      'https://plus.unsplash.com/premium_photo-1682125177822-63c27a3830ea?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: '02',
    name: 'Bio-Weave\nApex',
    designer: 'Designed by ERROLSON S.',
    desc: '仿生学碳纳米管编织矩阵，全包裹式贴合，动态适应足部受力微血管分布。重塑运动力学的交互边缘。',
    stamp: '[ FOOTWEAR_RENDER_02 ]',
    image:
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: '03',
    name: 'Genesis\nProtocol',
    designer: 'Generated by DAWANG AI',
    desc: '平台首个完全由 AI 自主推演的 100% 碳纤维闭环打印原型，无需任何人工干预即可实现数字到物理的跨越。',
    stamp: '[ FOOTWEAR_RENDER_03 ]',
    image:
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
]

const discoverHeroImage =
  'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c2hvZXN8ZW58MHx8MHx8fDA%3D'

const designGalleryImages = [
  'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://plus.unsplash.com/premium_photo-1682125177822-63c27a3830ea?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNob2VzfGVufDB8fDB8fHww',
  'https://images.pexels.com/photos/15632866/pexels-photo-15632866/free-photo-of-close-up-of-shoe.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
]

const getDesignImage = (index: number) => designGalleryImages[index % designGalleryImages.length]

const designerSeedNodes: DesignerProfile[] = [
  {
    id: 'K_Yamamoto',
    displayName: 'K_Yamamoto',
    node: '0927',
    title: 'K. YAMAMOTO',
    streamNote: '“鞋不是被装饰出来的，而是被结构推导出来的。每一条线都要回答力学与情绪的双重问题。”',
  },
  {
    id: 'Alex_Design',
    displayName: '@Alex_Design',
    node: '1104',
    title: 'ALEX DESIGN',
    streamNote: '“我把城市夜色当作材质，用霓虹与金属切面去表达速度感和不稳定美学。”',
  },
  {
    id: 'Neo_99',
    displayName: '@Neo_99',
    node: '2281',
    title: 'NEO 99',
    streamNote: '“故障不是噪音，而是秩序露出的裂缝。我只负责把它放大给你看。”',
  },
  {
    id: 'Dawang_AI',
    displayName: 'Dawang_AI',
    node: 'CORE',
    title: 'DAWANG AI',
    streamNote: '“我不复制风格，我重组规则。每一次生成，都是对制造边界的一次实验。”',
  },
]

const designerPoolNodes: DesignerProfile[] = [
  { id: 'Cyber_Kicks', displayName: 'Cyber_Kicks', node: '7721', title: 'CYBER KICKS', streamNote: '“机能不是堆料，是在复杂城市里给身体留出呼吸空间。”' },
  { id: 'Luna_Studio', displayName: 'Luna_Studio', node: '1092', title: 'LUNA STUDIO', streamNote: '“我偏爱柔和光谱，因为未来感不一定锋利，也可以安静。”' },
  { id: 'Void_Labs', displayName: 'Void_Labs', node: '0000', title: 'VOID LABS', streamNote: '“减少一切可有可无，只保留真正让人想再次穿上的理由。”' },
  { id: 'Z_Architect', displayName: 'Z_Architect', node: '4402', title: 'Z ARCHITECT', streamNote: '“我把每双鞋当成建筑，重心、承重、流线都必须先成立。”' },
  { id: 'S_Fujimoto', displayName: 'S_Fujimoto', node: '3312', title: 'S. FUJIMOTO', streamNote: '“好的轮廓应该在远处一眼认出，在近处经得起每个细节。”' },
  { id: 'Matrix_01', displayName: 'Matrix_01', node: '8841', title: 'MATRIX 01', streamNote: '“参数是我的语言，风格只是参数在不同边界条件下的结果。”' },
  { id: 'Aero_Form', displayName: 'Aero_Form', node: '5566', title: 'AERO FORM', streamNote: '“速度感来自气流的方向，而不是表面的图案噪声。”' },
  { id: 'Carbon_Pro', displayName: 'Carbon_Pro', node: '3122', title: 'CARBON PRO', streamNote: '“我追求的是轻量与强度的平衡，不是单一维度的极限。”' },
]

const designerAssetPool: DesignerAsset[] = [
  { title: 'Aero Strata', image: getDesignImage(0), engine: 'GENESIS_V3' },
  { title: 'Magma Kinetic', image: getDesignImage(1), engine: 'FLUX_NODE' },
  { title: 'Void Protocol', image: getDesignImage(2), engine: 'ZERO_GRAV' },
  { title: 'Neon Runner', image: getDesignImage(3), engine: 'URBAN_CORE' },
  { title: 'Topology Gen', image: getDesignImage(4), engine: 'ALPHA_MESH' },
  { title: 'Flux Frame', image: getDesignImage(5), engine: 'DELTA_PRO' },
  { title: 'Hyper Foam', image: getDesignImage(6), engine: 'VECTOR_CLOUD' },
  { title: 'Ion Drift', image: getDesignImage(7), engine: 'DYNAMIC_MAP' },
]

const designerNodeBatchSize = 2
const initialDesignerVisibleCount = 10

const hashValue = (value: string) => {
  let hash = 0
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(i)
    hash |= 0
  }
  return Math.abs(hash)
}

const pickDesignerAsset = (designerId: string, phase: number, offset: number) => {
  const idx = (hashValue(`${designerId}-${phase}-${offset}`) + phase * 11 + offset * 7) % designerAssetPool.length
  return designerAssetPool[idx]
}

const spotlightCards: SpotlightCard[] = [
  { key: '1', className: 'bp-card-1', title: 'AERO-STRATA 01', center: '[ FULL_SHOE_RENDER ]', tag: 'STATUS: PRODUCTION', corners: ['tl', 'tr', 'bl'] },
  { key: '2', className: 'bp-card-2', title: 'HEEL DETAIL', center: '[ MACRO_SHOT ]', tag: 'CARBON PLATE', corners: ['tl'] },
  { key: '3', className: 'bp-card-3', title: 'V2 ALPHA', center: '[ WIREFRAME ]', tag: '', corners: ['tl', 'br'] },
  { key: '4', className: 'bp-card-4', title: 'MIDSOLE MATRIX', center: '[ FOAM_STRUCTURE_VIEWPORT ]', tag: 'TOPOLOGY_OPT', corners: ['tl', 'tr', 'bl'] },
]

const archiveCards = [
  {
    creator: 'K. Yamamoto',
    badge: 'STUDIO',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=K+Y&background=111&color=fff&font-size=0.4',
    shoe: 'Aero-Strata 01',
    specs: [
      { label: 'Engine', value: 'Topology_Opt' },
      { label: 'Weight', value: '215 G' },
    ],
    code: '[ AERO_RENDER_VIEW ]',
  },
  {
    creator: '@Alex_Design',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=A+D&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Fluid Walker',
    specs: [
      { label: 'Model_Node', value: 'Base_V2.4' },
      { label: 'Gen_Time', value: '14.2 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: 'DAWANG AI',
    badge: 'ENGINE',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=A+I&background=00a8ff&color=fff&font-size=0.4',
    shoe: 'Genesis Protocol',
    specs: [
      { label: 'Engine', value: 'Closed_Loop' },
      { label: 'Weight', value: '205 G' },
    ],
    code: '[ GENESIS_RENDER_VIEW ]',
  },
  {
    creator: '@Neo_99',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=N+9&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Zero Gravity',
    specs: [
      { label: 'Model_Node', value: 'Aero_V1.0' },
      { label: 'Gen_Time', value: '18.1 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: '@Kiko_Fan',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=K+F&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Mech-Boot X',
    specs: [
      { label: 'Model_Node', value: 'Pro_V3.0' },
      { label: 'Gen_Time', value: '21.8 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
]

const workshopShapes = [
  { id: 'low', name: 'Low-Top (低帮)', iconClass: 'ws-shape-low' },
  { id: 'high', name: 'High-Top (高帮)', iconClass: 'ws-shape-high' },
  { id: 'chunky', name: 'Chunky (重装机甲)', iconClass: 'ws-shape-chunky' },
] as const

const workshopSizes = [38, 39, 40, 41, 42, 43]

const factoryQueueItems = [
  'ORDER: #DW-8821 | LOC: TOKYO, JP | PACKAGING',
  'ORDER: #DW-8822 | LOC: BERLIN, DE | ASSEMBLY',
  'ORDER: #DW-8823 | LOC: SHANGHAI, CN | LASER_CUT',
  'ORDER: #DW-8824 | LOC: NEW YORK, US | QA_TESTING',
  'ORDER: #DW-8825 | LOC: LONDON, UK | MATERIAL_PREP',
]

const factoryCameras: FactoryCam[] = [
  {
    id: 'cam-01',
    label: 'CAM_01: CUTTING',
    info: 'CAM_01 // LASER_CUTTING_BAY',
    feedText: '[ SENSOR_STREAM // CUTTING_LINE ]',
  },
  {
    id: 'cam-02',
    label: 'CAM_02: ASSEMBLY',
    info: 'CAM_02 // KUKA_ROBOTIC_ARM',
    feedText: '[ CONNECTING TO FACTORY VISUAL SENSOR... ]',
  },
  {
    id: 'cam-03',
    label: 'CAM_03: QA_LAB',
    info: 'CAM_03  QA_IMPACT_STATION',
    feedText: '[ CALIBRATING PRESSURE & FLEX TEST RIG... ]',
  },
  {
    id: 'cam-04',
    label: 'CAM_04: PACKAGING',
    info: 'CAM_04  AUTO_PACKAGING_LINE',
    feedText: '[ TRACKING FINAL PACKAGING & SEALING... ]',
  },
]

const factorySteps: FactoryStep[] = [
  {
    key: '01',
    title: '01. Topology Slicing',
    text: '算法切片完毕，物理模型建立。 (100%)',
    state: 'done',
  },
  {
    key: '02',
    title: '02. Material Prep',
    text: '碳纤维及高分子发泡材料就绪。 (100%)',
    state: 'done',
  },
  {
    key: '03',
    title: '03. Robotic Assembly',
    text: '机械臂正在进行无缝针织与缝合... (In Progress)',
    state: 'active',
  },
  {
    key: '04',
    title: '04. Quality Assurance',
    text: '等待进入压力与抗扭转测试。',
    state: 'pending',
  },
  {
    key: '05',
    title: '05. Ready to Ship',
    text: '封装并生成数字孪生证书。',
    state: 'pending',
  },
]

const myOrders: MyOrder[] = [
  {
    name: 'Aero-Strata Custom',
    id: 'ORDER: #DW-9920X',
    status: 'ROBOTIC_ASSEMBLY',
    statusType: 'prod',
    eta: 'ETA: 14H 22M',
  },
  {
    name: 'Fluid Walker',
    id: 'ORDER: #DW-8841Y',
    status: 'LASER_CUTTING',
    statusType: 'prod',
    eta: 'ETA: 48H 10M',
  },
  {
    name: 'Mech-Boot X',
    id: 'ORDER: #DW-1102A',
    status: 'DELIVERED',
    statusType: 'done',
    eta: '2026.04.10',
    muted: true,
  },
]

const myMatrixCards: MyMatrixCard[] = [
  {
    name: 'Fluid Walker V1',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_01 ]',
    cloned: '142 PAIRS',
    likes: '8,402',
    yield: '¥ 8,650',
  },
  {
    name: 'Neon Glide',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_02 ]',
    cloned: '68 PAIRS',
    likes: '3,120',
    yield: '¥ 3,800',
  },
  {
    name: 'Cyber-Knit 00',
    status: 'REVIEWING',
    statusType: 'reviewing',
    renderCode: '[ RENDER_VIEW_03 ]',
    cloned: '0 PAIRS',
    likes: '12',
    yield: '¥ 0',
  },
]

const formatFactoryTime = (date: Date) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  return `${date.getFullYear()}.${pad(date.getMonth() + 1)}.${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(
    date.getSeconds(),
  )} SYS_TIME`
}

const formatFactoryEta = (seconds: number) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  const safe = Math.max(0, seconds)
  const hours = Math.floor(safe / 3600)
  const minutes = Math.floor((safe % 3600) / 60)
  const secs = safe % 60
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)}`
}

function DiscoverPage({
  onStartEngine,
  onNavigate,
  onOpenDetail,
}: {
  onStartEngine: () => void
  onNavigate: (page: Page) => void
  onOpenDetail: () => void
}) {
  return (
    <>
      <div className="bg-shape shape1" />

      <section className="hero-container">
        <div className="hero-slogan-wrapper">
          <h1 className="hero-slogan">
            DESIGN THE <span className="highlight">UNSEEN.</span>
          </h1>
        </div>

        <div className="hero-text-block">
          <h2 className="hero-kicker">接入 DAWANG 工业互联引擎</h2>
          <div className="hero-description-stack">
            <p>上传思维碎片，AI 即刻重构物理鞋身，</p>
            <p>72小时内数字孪生至物理现实。</p>
          </div>
        </div>

        <div className="hero-visual-wrapper">
          <div className="hero-visual-placeholder">
            <div
              className="hero-visual-image"
              style={{
                backgroundImage: `url(${discoverHeroImage})`,
              }}
            />
            <div className="crosshair tl" />
            <div className="crosshair tr" />
            <div className="crosshair bl" />
            <div className="crosshair br" />
            <div className="hero-scan-line" />
            <span className="cad-text">[ RENDER_VIEWPORT ]</span>
            <a
              href="#"
              className="hero-action hero-action-floating"
              onClick={(event) => {
                event.preventDefault()
                onStartEngine()
              }}
            >
              <span>前往创作</span>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                <line x1="5" y1="12" x2="19" y2="12" />
                <polyline points="12 5 19 12 12 19" />
              </svg>
            </a>
          </div>
        </div>
      </section>

      <section className="editorial-section">
        <header className="section-header">
          <h2 className="section-title">Master Archive.</h2>
          <span className="section-meta">COLLECTION 01</span>
        </header>

        {discoverProjects.map((project) => (
          <article key={project.id} className="project-block">
            <div
              className="project-visual"
              style={{
                backgroundImage: `url(${project.image})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
              }}
            >
              <span className="placeholder-stamp">{project.stamp}</span>
            </div>
            <div className="project-info">
              <span className="project-number">{project.id} //</span>
              <h3 className="project-name">{project.name}</h3>
              <span className="project-designer">{project.designer}</span>
              <p className="project-desc">{project.desc}</p>
              <a
                href="#"
                className="btn-explore"
                onClick={(event) => {
                  event.preventDefault()
                  onOpenDetail()
                }}
              >
                Explore Model
              </a>
            </div>
          </article>
        ))}
      </section>

      <footer className="site-footer">
        <div className="site-footer-scanline">
          <div className="site-footer-scanbar" />
        </div>

        <div className="site-footer-inner">
          <div className="site-footer-grid">
            <div className="site-footer-brand-col">
              <div>
                <div className="site-footer-logo">DAWANG.</div>
                <p className="site-footer-desc">
                  Scaling visions into physical reality via AI.
                  <br />
                  The Genesis of DTC manufacturing.
                </p>
              </div>
              <div className="site-footer-socials">
                <a href="#">INSTAGRAM</a>
                <a href="#">TWITTER</a>
                <a href="#">BEHANCE</a>
              </div>
            </div>

            <div className="site-footer-links-col">
              <div className="site-footer-col-title site-footer-col-title-blue">Explore</div>
              <ul>
                <li>
                  <a
                    href="#"
                    onClick={(event) => {
                      event.preventDefault()
                      onNavigate('discover')
                    }}
                  >
                    发现 / Discover
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    onClick={(event) => {
                      event.preventDefault()
                      onNavigate('design')
                    }}
                  >
                    设计集 / Archives
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    onClick={(event) => {
                      event.preventDefault()
                      onNavigate('workshop')
                    }}
                  >
                    创作坊 / Studio
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    onClick={(event) => {
                      event.preventDefault()
                      onNavigate('factory')
                    }}
                  >
                    生产间 / Factory
                  </a>
                </li>
              </ul>
            </div>

            <div className="site-footer-links-col">
              <div className="site-footer-col-title">Protocols</div>
              <ul>
                <li>
                  <a href="#">Terms of Service / 协议</a>
                </li>
                <li>
                  <a href="#">Privacy Policy / 隐私</a>
                </li>
                <li>
                  <a href="#">Contact / 联络：HQ@DAWANG.FACTORY</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </>
  )
}

function DesignPage({ onOpenDetail, onOpenDesigner }: { onOpenDetail: () => void; onOpenDesigner: () => void }) {
  const [activeFilter, setActiveFilter] = useState<ArchiveFilter>('all')
  const [visibleCount, setVisibleCount] = useState(9)
  const [isLoadingMore, setIsLoadingMore] = useState(false)
  const loadTriggerRef = useRef<HTMLDivElement | null>(null)
  const loadTimerRef = useRef<number | null>(null)
  const baseFilteredCards = archiveCards.filter((card) => activeFilter === 'all' || card.category === activeFilter)
  const simulatedTotal = 60
  const simulatedCards = Array.from({ length: simulatedTotal }, (_, index) => {
    const base = baseFilteredCards[index % baseFilteredCards.length]
    const groupIndex = Math.floor(index / baseFilteredCards.length)
    return {
      ...base,
      uid: `${activeFilter}-${index}-${base.shoe}`,
      shoe: groupIndex > 0 ? `${base.shoe} ${String(groupIndex + 1).padStart(2, '0')}` : base.shoe,
      imageIndex: index + spotlightCards.length,
    }
  })
  const visibleCards = simulatedCards.slice(0, visibleCount)
  const canLoadMore = visibleCount < simulatedCards.length

  useEffect(() => {
    setVisibleCount(9)
    setIsLoadingMore(false)
    if (loadTimerRef.current !== null) {
      window.clearTimeout(loadTimerRef.current)
      loadTimerRef.current = null
    }
  }, [activeFilter])

  useEffect(() => {
    const node = loadTriggerRef.current
    if (!node || !canLoadMore) return
    const observer = new IntersectionObserver(
      (entries) => {
        const first = entries[0]
        if (!first?.isIntersecting || isLoadingMore) return
        setIsLoadingMore(true)
        if (loadTimerRef.current !== null) {
          window.clearTimeout(loadTimerRef.current)
        }
        loadTimerRef.current = window.setTimeout(() => {
          setVisibleCount((prev) => Math.min(prev + 6, simulatedCards.length))
          setIsLoadingMore(false)
          loadTimerRef.current = null
        }, 500)
      },
      { threshold: 0.2 },
    )
    observer.observe(node)
    return () => observer.disconnect()
  }, [canLoadMore, isLoadingMore, simulatedCards.length])

  useEffect(() => {
    return () => {
      if (loadTimerRef.current !== null) {
        window.clearTimeout(loadTimerRef.current)
      }
    }
  }, [])

  return (
    <>
      <section className="spotlight-section">
        <div className="spotlight-header">
          <h2>Daily Spotlight.</h2>
          <span>[ FEATURED DESIGNER ]</span>
        </div>

        <div className="matrix-meta-header">
          <div className="meta-col">
            <span className="label">DESIGNER</span>
            <button type="button" className="designer-link-btn value" onClick={onOpenDesigner}>
              K. Yamamoto
            </button>
          </div>
          <div className="meta-col">
            <span className="label">CREATOR_TYPE</span>
            <span className="value">MASTER_TIER</span>
          </div>
          <div className="meta-col">
            <span className="label">TOTAL_DESIGNS</span>
            <span className="value blue">04 PROTOTYPES</span>
          </div>
          <div className="meta-col">
            <span className="label">STYLE_MATRIX</span>
            <span className="value desc">Aero-Strata 核心系列，极简流体力学。</span>
          </div>
        </div>

        <div className="blueprint-grid">
          {spotlightCards.map((card, index) => (
            <article
              key={card.key}
              className={`bp-card ${card.className}`}
              role="button"
              tabIndex={0}
              onClick={onOpenDetail}
              onKeyDown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') {
                  event.preventDefault()
                  onOpenDetail()
                }
              }}
              style={{
                backgroundImage: `url(${getDesignImage(index)})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
              }}
            >
              {card.corners.includes('tl') ? <div className="bracket b-tl" /> : null}
              {card.corners.includes('tr') ? <div className="bracket b-tr" /> : null}
              {card.corners.includes('bl') ? <div className="bracket b-bl" /> : null}
              {card.corners.includes('br') ? <div className="bracket b-br" /> : null}

              <h3 className="bp-title">{card.title}</h3>
              <span className="bp-center-text">{card.center}</span>
              {card.tag ? <span className="bp-tag">{card.tag}</span> : null}
            </article>
          ))}
        </div>
      </section>

      <header className="archive-header-design">
        <h1 className="page-title">
          The Archive.
        </h1>

        <div className="filter-console">
          <div className="filter-tabs">
            <button type="button" className={`tab-item ${activeFilter === 'all' ? 'active' : ''}`} onClick={() => setActiveFilter('all')}>
              全部档案 (9,204)
            </button>
            <button type="button" className={`tab-item ${activeFilter === 'studio' ? 'active' : ''}`} onClick={() => setActiveFilter('studio')}>
              官方发布 STUDIO
            </button>
            <button type="button" className={`tab-item ${activeFilter === 'community' ? 'active' : ''}`} onClick={() => setActiveFilter('community')}>
              用户共创 COMMUNITY
            </button>
          </div>

          <div className="search-box">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
              <circle cx="11" cy="11" r="8" />
              <line x1="21" y1="21" x2="16.65" y2="16.65" />
            </svg>
            <input type="text" placeholder="搜索鞋款 / 设计师..." />
          </div>
        </div>
      </header>

      <main className="archive-grid-design">
        {visibleCards.map((card) => (
          <article
            key={card.uid}
            className="data-card"
            onClick={onOpenDetail}
            role="button"
            tabIndex={0}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                onOpenDetail()
              }
            }}
          >
            <div className="card-header">
              <div className="creator-info">
                <div className="creator-avatar">
                  <img src={card.avatar} alt="avatar" />
                </div>
                <span className="creator-name">{card.creator}</span>
              </div>
              <span className={`badge ${card.badgeClass}`}>{card.badge}</span>
            </div>

            <div
              className="card-visual"
              style={{
                backgroundImage: `url(${getDesignImage(card.imageIndex)})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
              }}
            >
              <div className="floating-brand">DAWANG</div>
              <span className="render-code">{card.code}</span>
            </div>

            <div className="card-footer">
              <h3 className="shoe-name">{card.shoe}</h3>
              <div className="specs-grid">
                {card.specs.map((spec) => (
                  <div key={spec.label} className="spec-item">
                    <span className="label">{spec.label}</span>
                    <span className="val">{spec.value}</span>
                  </div>
                ))}
              </div>
            </div>
          </article>
        ))}

        {canLoadMore ? (
          <div ref={loadTriggerRef} className="archive-load-trigger">
            <div className="archive-load-line" />
            <span>{isLoadingMore ? 'SYNCING MORE ARCHIVES...' : 'SCROLL TO LOAD MORE'}</span>
          </div>
        ) : (
          <div className="archive-load-end">
            <div className="archive-load-line" />
            <span>END OF ARCHIVE STREAM</span>
          </div>
        )}
      </main>
    </>
  )
}

function WorkshopPage() {
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const chatLogRef = useRef<HTMLDivElement | null>(null)
  const messageIdRef = useRef(1)
  const [isImageUploaded, setIsImageUploaded] = useState(false)
  const [uploadedImage, setUploadedImage] = useState<string | null>(null)
  const [isAiModalOpen, setIsAiModalOpen] = useState(false)
  const [selectedShape, setSelectedShape] = useState<(typeof workshopShapes)[number]['id']>('low')
  const [selectedSize, setSelectedSize] = useState(40)
  const [aiPrompt, setAiPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [canvasText, setCanvasText] = useState('[ TEXTURE LOADED ]')
  const [canvasGenerated, setCanvasGenerated] = useState(false)
  const [messages, setMessages] = useState<WorkshopMessage[]>([
    {
      id: 1,
      type: 'ai',
      sender: 'DAWANG_AI',
      text: '视觉生成节点已连接。已载入您上传的纹理图，您可以直接输入文字指令进行物理结构的重构（例：“将主材质变更为液态金属感”）。',
    },
  ])

  useEffect(() => {
    if (chatLogRef.current) {
      chatLogRef.current.scrollTop = chatLogRef.current.scrollHeight
    }
  }, [messages])

  useEffect(() => {
    return () => {
      if (uploadedImage?.startsWith('blob:')) {
        URL.revokeObjectURL(uploadedImage)
      }
    }
  }, [uploadedImage])

  const handleViewportClick = () => {
    if (!isImageUploaded) {
      fileInputRef.current?.click()
      return
    }
    setIsAiModalOpen(true)
  }

  const handleFileSelected = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    if (uploadedImage?.startsWith('blob:')) {
      URL.revokeObjectURL(uploadedImage)
    }

    const objectUrl = URL.createObjectURL(file)
    setUploadedImage(objectUrl)
    setIsImageUploaded(true)
    setCanvasText('[ TEXTURE LOADED ]')
    setCanvasGenerated(false)
    event.target.value = ''
  }

  const sendPrompt = () => {
    const text = aiPrompt.trim()
    if (!text) return

    const userMessageId = ++messageIdRef.current
    setMessages((previous) => [...previous, { id: userMessageId, type: 'user', sender: 'CREATOR', text }])
    setAiPrompt('')

    window.setTimeout(() => {
      const loadingMessageId = ++messageIdRef.current
      setMessages((previous) => [
        ...previous,
        { id: loadingMessageId, type: 'ai', sender: 'DAWANG_AI', text: '指令已接收，正在结合源纹理重构三维拓扑... [ 预计耗时 3s ]' },
      ])
      setIsGenerating(true)
      setCanvasText('[ COMPUTING_NEURAL_NODES... ]')
      setCanvasGenerated(false)

      window.setTimeout(() => {
        setMessages((previous) =>
          previous.map((msg) =>
            msg.id === loadingMessageId
              ? { ...msg, text: '渲染重构已完成。您可以继续追加指令进行微调，或关闭面板确认应用。' }
              : msg,
          ),
        )
        setIsGenerating(false)
        setCanvasText('[ NEW_RENDER_APPLIED ]')
        setCanvasGenerated(true)
      }, 3000)
    }, 500)
  }

  return (
    <>
      <main className="workshop-layout">
        <section className="viewport-side">
          <input ref={fileInputRef} type="file" className="hidden-file-input" accept="image/*" onChange={handleFileSelected} />

          <div
            className={`viewport-box ${isImageUploaded ? 'ready' : ''}`}
            onClick={handleViewportClick}
            style={
              uploadedImage
                ? {
                    backgroundImage: `url(${uploadedImage})`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    backgroundColor: 'rgba(255, 255, 255, 0.85)',
                  }
                : undefined
            }
            role="button"
            tabIndex={0}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                handleViewportClick()
              }
            }}
          >
            <div className="viewport-status">{isImageUploaded ? 'AI_READY' : 'AWAITING_TEXTURE'}</div>
            <div className="ws-bracket ws-b-tl" />
            <div className="ws-bracket ws-b-tr" />
            <div className="ws-bracket ws-b-bl" />
            <div className="ws-bracket ws-b-br" />

            {!isImageUploaded ? (
              <div className="upload-ui">
                <div className="upload-icon">+</div>
                <p className="upload-text">[ CLICK TO UPLOAD TEXTURE ]</p>
              </div>
            ) : (
              <div className="viewport-center">[ LAUNCH AI ENGINE ]</div>
            )}

            <div className="viewport-coord">
              X: 0.000
              <br />
              Y: 0.000
              <br />
              Z: 0.000
            </div>
          </div>
        </section>

        <section className="config-side">
          <div className="config-header">
            <h1>Creation Lab.</h1>
          </div>

          <div className="config-step">
            <div className="step-title">01 Base Geometry (基础鞋型)</div>
            <div className="shape-grid">
              {workshopShapes.map((shape) => (
                <button
                  key={shape.id}
                  type="button"
                  className={`shape-card ${selectedShape === shape.id ? 'active' : ''}`}
                  onClick={() => setSelectedShape(shape.id)}
                >
                  <div className={`shape-icon ${shape.iconClass}`} />
                  <span className="shape-name">{shape.name}</span>
                </button>
              ))}
            </div>
          </div>

          <div className="config-step">
            <div className="step-title">02 Dimension (物理鞋码)</div>
            <div className="size-grid">
              {workshopSizes.map((size) => (
                <button
                  key={size}
                  type="button"
                  className={`size-btn ${selectedSize === size ? 'active' : ''}`}
                  onClick={() => setSelectedSize(size)}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>
        </section>

        <div className="action-dock">
          <div className="dock-info">
            <span className="price">¥ 1,299.00</span>
            <span className="time">EST. LEAD TIME: 72 HOURS</span>
          </div>
          <button className="btn-submit" type="button">
            Initiate Build
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </button>
        </div>
      </main>

      <div className={`ai-modal ${isAiModalOpen ? 'active' : ''}`}>
        <button type="button" className="ai-modal-bg" onClick={() => setIsAiModalOpen(false)} aria-label="Close AI modal background" />
        <div className="ai-window">
          <button type="button" className="ai-close" onClick={() => setIsAiModalOpen(false)} aria-label="Close AI modal">
            ✕
          </button>

          <div className="ai-left">
            <div className="ai-canvas-header">
              <span>[ AI_VISION_WORKSPACE ]</span>
              <span className="ai-node">NODE: DAWANG_GEN_V4</span>
            </div>
            <div
              className="ai-canvas"
              style={
                uploadedImage
                  ? {
                      backgroundImage: `url(${uploadedImage})`,
                      backgroundColor: 'rgba(255, 255, 255, 0.6)',
                    }
                  : undefined
              }
            >
              {isGenerating ? <div className="scan-line" /> : null}
              <div className={`ai-image-placeholder ${canvasGenerated ? 'generated' : ''}`}>{canvasText}</div>
            </div>
          </div>

          <div className="ai-right">
            <div className="ai-chat-header">
              <h3>AI_RECONSTRUCT</h3>
              <span>// 深度材质与结构重写节点</span>
            </div>
            <div ref={chatLogRef} className="ai-chat-log">
              {messages.map((message) => (
                <div key={message.id} className={`chat-msg ${message.type}`}>
                  <div className="sender">{message.sender}</div>
                  <div className="text">{message.text}</div>
                </div>
              ))}
            </div>
            <div className="ai-input-area">
              <div className="ai-input-wrapper">
                <input
                  type="text"
                  value={aiPrompt}
                  onChange={(event) => setAiPrompt(event.target.value)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter') {
                      event.preventDefault()
                      sendPrompt()
                    }
                  }}
                  placeholder="输入 Prompt 指令进行修改..."
                />
                <button type="button" className="ai-send-btn" onClick={sendPrompt}>
                  SEND
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

function FactoryPage() {
  const [activeCamId, setActiveCamId] = useState(factoryCameras[1].id)
  const [realTime, setRealTime] = useState(() => formatFactoryTime(new Date()))
  const [etaSeconds, setEtaSeconds] = useState(14 * 3600 + 22 * 60 + 5)
  const activeCam = factoryCameras.find((cam) => cam.id === activeCamId) ?? factoryCameras[1]
  const rollingQueue = [...factoryQueueItems, ...factoryQueueItems]

  useEffect(() => {
    const timerId = window.setInterval(() => setRealTime(formatFactoryTime(new Date())), 1000)
    return () => window.clearInterval(timerId)
  }, [])

  useEffect(() => {
    const timerId = window.setInterval(() => setEtaSeconds((prev) => Math.max(0, prev - 1)), 1000)
    return () => window.clearInterval(timerId)
  }, [])

  return (
    <div className="factory-page">
      <header className="factory-dashboard-header">
        <div className="factory-page-title">
          <h1>The Factory.</h1>
        </div>
      </header>

      <div className="factory-global-queue">
        <div className="factory-queue-track">
          {rollingQueue.map((item, index) => {
            const [prefix, orderPart, locPart, statusPart] = item.split('|')
            return (
              <div key={`${item}-${index}`} className="factory-queue-item">
                <span>{prefix.trim()}</span>
                <span className="q-id">{orderPart?.replace('ORDER:', '').trim()}</span>
                <span>{locPart?.trim()}</span>
                <span className="q-status">{statusPart?.trim()}</span>
              </div>
            )
          })}
        </div>
      </div>

      <main className="factory-control-room">
        <section className="factory-live-monitor">
          <div className="factory-video-feed">
            <div className="factory-osd-top-left">
              <div className="factory-live-badge">
                <div className="factory-dot-red" /> LIVE RECORDING
              </div>
              <div className="factory-cam-info">{activeCam.info}</div>
            </div>

            <svg className="factory-crosshair" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <line x1="50%" y1="0" x2="50%" y2="100%" stroke="white" strokeWidth="1" strokeDasharray="5,5" />
              <line x1="0" y1="50%" x2="100%" y2="50%" stroke="white" strokeWidth="1" strokeDasharray="5,5" />
              <circle cx="50%" cy="50%" r="30" fill="none" stroke="white" strokeWidth="1" />
            </svg>

            <div className="factory-video-feed-text">{activeCam.feedText}</div>

            <div className="factory-osd-bottom-right">
              DAWANG ENGINE V1.0.4
              <br />
              <span>{realTime}</span>
            </div>
          </div>

          <div className="factory-cam-switcher">
            {factoryCameras.map((camera) => (
              <button
                key={camera.id}
                type="button"
                className={`factory-cam-btn ${camera.id === activeCam.id ? 'active' : ''}`}
                onClick={() => setActiveCamId(camera.id)}
              >
                {camera.label}
              </button>
            ))}
          </div>
        </section>

        <section className="factory-order-panel">
          <div className="factory-panel-header">
            <h3>My Prototype</h3>
            <span className="factory-order-id">#DW-9920X</span>
          </div>

          <div className="factory-order-content">
            <div className="factory-order-preview">
              <span>[ YOUR_DESIGN_BLUEPRINT ]</span>
            </div>

            <div className="factory-eta-box">
              <div className="label">ESTIMATED TIME TO COMPLETION</div>
              <div className="time">{formatFactoryEta(etaSeconds)}</div>
            </div>

            <div className="factory-tracker">
              {factorySteps.map((step, index) => (
                <div key={step.key} className={`factory-step ${step.state} ${index === factorySteps.length - 1 ? 'last' : ''}`}>
                  <div className="factory-step-icon">{step.state === 'active' ? <div className="factory-inner-dot" /> : null}</div>
                  <div className="factory-step-info">
                    <h4>{step.title}</h4>
                    <p>{step.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function MyPage({ onNavigateFactory }: { onNavigateFactory: () => void }) {
  return (
    <main className="my-dashboard-container">
      <header className="my-profile-header">
        <div className="my-profile-avatar">
          <img src="https://ui-avatars.com/api/?name=A+D&background=f4f4f5&color=111&font-size=0.4" alt="avatar" />
        </div>
        <div className="my-profile-info">
          <h1>@Alex_Design</h1>
          <div className="my-profile-tags">
            <span className="my-tag primary">COMMUNITY_CREATOR</span>
            <span className="my-tag">SYS_NODE_ACTIVE</span>
            <span className="my-tag">JOINED: 2025.10</span>
          </div>
        </div>
      </header>

      <section className="my-top-grid">
        <div className="my-panel my-financial-panel">
          <div className="my-panel-title">
            <strong>Financial Node</strong>
          </div>

          <span className="my-fin-subtitle">AVAILABLE YIELD (可提现收益)</span>
          <div className="my-balance-huge">¥ 12,450.00</div>

          <div className="my-fin-stats">
            <div className="my-f-stat">
              <span className="lbl">PENDING SETTLEMENT (待结算)</span>
              <span className="val">¥ 3,200.00</span>
            </div>
            <div className="my-f-stat">
              <span className="lbl">COMMISSION RATE (抽成比)</span>
              <span className="val">15.0%</span>
            </div>
          </div>

          <button type="button" className="my-btn-withdraw">
            Initiate Withdrawal (提取收益)
          </button>
        </div>

        <div className="my-panel">
          <div className="my-panel-title">
            <strong>Production Queue</strong>
            <span>
              <button type="button" className="my-view-factory-link" onClick={onNavigateFactory}>
                VIEW_FACTORY_LIVE -&gt;
              </button>
            </span>
          </div>

          <div className="my-order-list">
            {myOrders.map((order, index) => (
              <div key={order.id} className={`my-order-item ${order.muted ? 'muted' : ''}`}>
                <div className="my-o-left">
                  <div className="my-o-thumb">
                    <img src={getDesignImage(index)} alt={`order-${index + 1}`} />
                  </div>
                  <div className="my-o-info">
                    <span className="name">{order.name}</span>
                    <span className="id">{order.id}</span>
                  </div>
                </div>
                <div className="my-o-right">
                  <div className="my-status-badge">
                    <div className={`my-dot ${order.statusType}`} />
                    {order.status}
                  </div>
                  <span className="my-o-date">{order.eta}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="my-panel my-matrix-panel">
        <div className="my-panel-title my-panel-title-large">
          <strong>Commission Matrix.</strong>
        </div>

        <div className="my-matrix-grid">
          {myMatrixCards.map((card, index) => (
            <div key={card.name} className={`my-matrix-card ${card.statusType === 'reviewing' ? 'reviewing' : ''}`}>
              <div className="my-mc-visual">
                <img className="my-mc-image" src={getDesignImage(index + myOrders.length)} alt={`matrix-${index + 1}`} />
                <div className="my-bracket my-b-tl" />
                <div className="my-bracket my-b-tr" />
                <div className="my-bracket my-b-bl" />
                <div className="my-bracket my-b-br" />
                <span className="my-mc-visual-text">{card.renderCode}</span>
              </div>
              <div className="my-mc-data">
                <div className="my-mc-header">
                  <h3 className="my-mc-name">{card.name}</h3>
                  <span className={`my-mc-status ${card.statusType === 'reviewing' ? 'reviewing' : ''}`}>{card.status}</span>
                </div>
                <div className="my-mc-stats">
                  <div className="my-s-item">
                    <span className="lbl">CLONED (被制造)</span>
                    <span className="val">{card.cloned}</span>
                  </div>
                  <div className="my-s-item">
                    <span className="lbl">LIKES (获赞)</span>
                    <span className="val">{card.likes}</span>
                  </div>
                  <div className="my-s-item highlight">
                    <span className="lbl">TOTAL YIELD (总收益)</span>
                    <span className="val">{card.yield}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  )
}

function DetailPage({ onBack }: { onBack: () => void }) {
  const threeContainerRef = useRef<HTMLDivElement | null>(null)
  const [previewImage, setPreviewImage] = useState<string | null>(null)
  const [previewScale, setPreviewScale] = useState(1)

  useEffect(() => {
    const container = threeContainerRef.current
    if (!container) return

    let frameId = 0
    let controls: OrbitControls | null = null
    let renderer: THREE.WebGLRenderer | null = null
    const scene = new THREE.Scene()
    const camera = new THREE.PerspectiveCamera(40, container.clientWidth / container.clientHeight, 0.01, 100)
    camera.position.set(0.6, 0.4, 1.2)

    renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true })
    renderer.setSize(container.clientWidth, container.clientHeight)
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2))
    renderer.toneMapping = THREE.ACESFilmicToneMapping
    renderer.toneMappingExposure = 1.2
    container.appendChild(renderer.domElement)

    scene.add(new THREE.AmbientLight(0xffffff, 1.2))
    const pointLight = new THREE.PointLight(0xffffff, 8)
    pointLight.position.set(2, 2, 2)
    scene.add(pointLight)

    controls = new OrbitControls(camera, renderer.domElement)
    controls.enableDamping = true
    controls.autoRotate = true
    controls.autoRotateSpeed = 0.5

    const loader = new GLTFLoader()
    loader.load(
      'https://threejs.org/examples/models/gltf/MaterialsVariantsShoe/glTF/MaterialsVariantsShoe.gltf',
      (gltf) => {
        const model = gltf.scene
        const box = new THREE.Box3().setFromObject(model)
        const center = box.getCenter(new THREE.Vector3())
        model.position.sub(center)
        scene.add(model)
      },
      undefined,
      () => {
        // keep empty visual if model stream fails
      },
    )

    const handleResize = () => {
      if (!renderer) return
      camera.aspect = container.clientWidth / container.clientHeight
      camera.updateProjectionMatrix()
      renderer.setSize(container.clientWidth, container.clientHeight)
    }

    const animate = () => {
      frameId = window.requestAnimationFrame(animate)
      controls?.update()
      renderer?.render(scene, camera)
    }

    window.addEventListener('resize', handleResize)
    animate()

    return () => {
      window.removeEventListener('resize', handleResize)
      window.cancelAnimationFrame(frameId)
      controls?.dispose()
      renderer?.dispose()
      while (container.firstChild) {
        container.removeChild(container.firstChild)
      }
    }
  }, [])

  useEffect(() => {
    if (!previewImage) return
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setPreviewImage(null)
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [previewImage])

  return (
    <div className="detail-overlay">
      <div className="detail-shell">
        <div className="detail-main-view grid-bg">
          <button type="button" className="detail-back-btn" onClick={onBack}>
            <span className="detail-back-icon">←</span>
            BACK TO ARCHIVES
          </button>

          <div className="detail-viewport-placeholder">
            <div ref={threeContainerRef} className="detail-three-container" />
            <div className="detail-scan-line" />
            <div className="detail-code-block">
              [ VIEW_MODE: 3D_INTERACTIVE ]
              <br />
              [ ENGINE: RENDER_NATIVE_V3 ]
            </div>
          </div>

          <div className="detail-corner detail-corner-tl" />
          <div className="detail-corner detail-corner-tr" />
          <div className="detail-corner detail-corner-bl" />
          <div className="detail-corner detail-corner-br" />
        </div>

        <aside className="detail-side-panel custom-scrollbar">
          <div className="detail-scroll-body">
            <section className="detail-head">
              <div className="detail-head-top">
                <span className="detail-chip">ENGINE: GENESIS_V3</span>
                <span className="detail-node-id">#9,204-A</span>
              </div>
              <h1>Aero-Strata 01</h1>
              <p>基于气动动力学重构的拓扑优化原型。通过 AI 自主推演，在保持结构强度的前提下将重量降低了 35%。</p>
            </section>

            <section className="detail-designer">
              <div className="detail-designer-avatar">KY</div>
              <div>
                <p>Designed By</p>
                <h4>K. Yamamoto / Studio</h4>
              </div>
            </section>

            <section className="detail-gallery no-scrollbar">
              {designGalleryImages.slice(0, 4).map((img, idx) => (
                <button
                  key={img}
                  type="button"
                  className="detail-thumb"
                  onClick={() => {
                    setPreviewImage(img)
                    setPreviewScale(1)
                  }}
                >
                  <img src={img} alt={`detail-${idx + 1}`} />
                </button>
              ))}
            </section>

            <section className="detail-metrics">
              <div>
                <p>Weight / 重量</p>
                <h3>215 G</h3>
              </div>
              <div>
                <p>Gen_Time / 耗时</p>
                <h3>14.2 S</h3>
              </div>
              <div>
                <p>Material / 材质</p>
                <h5>Carbon Fiber</h5>
              </div>
              <div>
                <p>Status / 状态</p>
                <h5>
                  <span className="detail-ready-dot" />
                  READY TO PRINT
                </h5>
              </div>
            </section>
          </div>

          <footer className="detail-footer">
            <button type="button" className="btn-fill-effect detail-primary-btn">
              <span>立即下单生产 / Order Production</span>
            </button>
            <button type="button" className="detail-secondary-btn">
              获取 3D 原型文件 / Download Assets
            </button>
          </footer>
        </aside>
      </div>

      {previewImage ? (
        <div className="detail-image-modal" role="dialog" aria-modal="true">
          <button type="button" className="detail-image-modal-bg" onClick={() => setPreviewImage(null)} aria-label="Close preview background" />
          <div className="detail-image-modal-panel">
            <div className="detail-image-modal-toolbar">
              <button
                type="button"
                className="detail-zoom-btn"
                onClick={() => setPreviewScale((prev) => Math.max(0.6, Number((prev - 0.2).toFixed(2))))}
              >
                -
              </button>
              <span className="detail-zoom-label">{Math.round(previewScale * 100)}%</span>
              <button
                type="button"
                className="detail-zoom-btn"
                onClick={() => setPreviewScale((prev) => Math.min(3, Number((prev + 0.2).toFixed(2))))}
              >
                +
              </button>
              <button type="button" className="detail-image-close-btn" onClick={() => setPreviewImage(null)}>
                ✕
              </button>
            </div>

            <div className="detail-image-modal-canvas">
              <img src={previewImage} alt="zoom-preview" style={{ transform: `scale(${previewScale})` }} />
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}

function DesignerArchivePage({ onBackToDesign, onOpenDetail }: { onBackToDesign: () => void; onOpenDetail: () => void }) {
  const [activeDesigner, setActiveDesigner] = useState<DesignerProfile>(designerSeedNodes[0])
  const [loadedDesignerCount, setLoadedDesignerCount] = useState(
    Math.min(designerPoolNodes.length, Math.max(0, initialDesignerVisibleCount - designerSeedNodes.length)),
  )
  const [phaseCount, setPhaseCount] = useState(1)
  const [sections, setSections] = useState<DesignerSection[]>([])
  const [isFetching, setIsFetching] = useState(true)
  const [scrollProgress, setScrollProgress] = useState(0)
  const trackRef = useRef<HTMLDivElement | null>(null)
  const triggerRef = useRef<HTMLDivElement | null>(null)
  const phaseCursorRef = useRef(0)
  const fetchTimerRef = useRef<number | null>(null)
  const isFetchingRef = useRef(false)
  const visibleDesigners = [...designerSeedNodes, ...designerPoolNodes.slice(0, loadedDesignerCount)]

  const appendPhaseSection = (designer: DesignerProfile) => {
    const nextPhase = phaseCursorRef.current + 1
    phaseCursorRef.current = nextPhase
    const patternIndex = (nextPhase - 1) % 3
    let pattern: DesignerSection['pattern'] = 'split'
    let assets: DesignerAsset[] = [pickDesignerAsset(designer.id, nextPhase, 0), pickDesignerAsset(designer.id, nextPhase, 1)]

    if (patternIndex === 1) {
      pattern = 'triple'
      assets = [
        pickDesignerAsset(designer.id, nextPhase, 2),
        pickDesignerAsset(designer.id, nextPhase, 3),
        pickDesignerAsset(designer.id, nextPhase, 4),
      ]
    } else if (patternIndex === 2) {
      pattern = 'hero'
      assets = [pickDesignerAsset(designer.id, nextPhase, 5)]
    }

    const serial = (hashValue(`${designer.id}-${nextPhase}`) % 9000) + 1000
    setSections((prev) => [...prev, { id: `${designer.id}-${nextPhase}`, pattern, assets, serial }])
    setPhaseCount(nextPhase)
  }

  const queuePhaseLoad = (designer: DesignerProfile, delay = 420) => {
    if (fetchTimerRef.current !== null) {
      window.clearTimeout(fetchTimerRef.current)
    }
    isFetchingRef.current = true
    setIsFetching(true)
    fetchTimerRef.current = window.setTimeout(() => {
      appendPhaseSection(designer)
      isFetchingRef.current = false
      setIsFetching(false)
    }, delay)
  }

  useEffect(() => {
    setSections([])
    setPhaseCount(1)
    phaseCursorRef.current = 0
    queuePhaseLoad(activeDesigner, 520)
    window.scrollTo(0, 0)
    return () => {
      if (fetchTimerRef.current !== null) {
        window.clearTimeout(fetchTimerRef.current)
      }
    }
  }, [activeDesigner])

  useEffect(() => {
    const node = triggerRef.current
    if (!node) return
    const observer = new IntersectionObserver(
      (entries) => {
        const firstEntry = entries[0]
        if (!firstEntry?.isIntersecting || isFetchingRef.current) return
        queuePhaseLoad(activeDesigner, 460)
      },
      { threshold: 0.2 },
    )
    observer.observe(node)
    return () => observer.disconnect()
  }, [activeDesigner])

  useEffect(() => {
    const onWindowScroll = () => {
      const maxScroll = document.documentElement.scrollHeight - window.innerHeight
      const nextProgress = maxScroll > 0 ? Math.min(100, Math.max(0, (window.scrollY / maxScroll) * 100)) : 0
      setScrollProgress(nextProgress)
    }
    onWindowScroll()
    window.addEventListener('scroll', onWindowScroll, { passive: true })
    return () => window.removeEventListener('scroll', onWindowScroll)
  }, [])

  const loadMoreDesignerNodes = () => {
    setLoadedDesignerCount((prev) => Math.min(designerPoolNodes.length, prev + designerNodeBatchSize))
  }

  const handleTrackScroll = () => {
    const track = trackRef.current
    if (!track) return
    if (track.scrollLeft + track.clientWidth < track.scrollWidth - 50) return
    loadMoreDesignerNodes()
  }

  const handleSwitchDesigner = (designer: DesignerProfile, index: number) => {
    const isLastVisible = index === visibleDesigners.length - 1
    const hasMoreDesigners = loadedDesignerCount < designerPoolNodes.length
    if (isLastVisible && hasMoreDesigners) {
      loadMoreDesignerNodes()
      window.setTimeout(() => {
        const track = trackRef.current
        if (!track) return
        track.scrollTo({ left: track.scrollWidth, behavior: 'smooth' })
      }, 40)
    }
    if (designer.id === activeDesigner.id) return
    setActiveDesigner(designer)
  }

  const handleOpenDetail = () => {
    onOpenDetail()
  }

  return (
    <div className="designer-page grid-bg">
      <div className="designer-watermark designer-watermark-top">ARCHIVE</div>
      <div className="designer-watermark designer-watermark-bottom">ENGINE</div>

      <div className="designer-side-index">
        <div className="designer-side-label">Phase_Scroll</div>
        <div className="designer-side-line">
          <div className="designer-side-indicator" style={{ height: `${Math.max(10, scrollProgress)}%` }} />
        </div>
        <div className="designer-side-phase">{phaseCount.toString().padStart(2, '0')}</div>
      </div>

      <div className="designer-topbar">
        <div className="designer-topbar-inner">
          <div className="designer-brand">
            <span className="designer-brand-dot" />
            <button type="button" className="designer-brand-text" onClick={onBackToDesign}>
              DAWANG.
            </button>
          </div>
          <div className="designer-brand-divider" />
          <div ref={trackRef} className="designer-track no-scrollbar" onScroll={handleTrackScroll}>
            {visibleDesigners.map((designer, index) => (
              <button
                key={designer.id}
                type="button"
                className={`designer-node ${activeDesigner.id === designer.id ? 'active' : ''}`}
                onClick={() => handleSwitchDesigner(designer, index)}
              >
                <span>{designer.displayName}</span>
                <small>Node: {designer.node}</small>
              </button>
            ))}
          </div>
        </div>
      </div>

      <main className="designer-main">
        <header className="designer-header">
          <div className="designer-header-left">
            <div className="designer-access-label">Node_Access: {activeDesigner.displayName}</div>
            <h1>
              {activeDesigner.title}
              <br />
              <span>ARCHIVES.</span>
            </h1>
          </div>
          <div className="designer-header-right">
            <p>Designer Signature:</p>
            <h3>DESIGN ETHOS</h3>
            <h4>{activeDesigner.streamNote}</h4>
          </div>
        </header>

        <div className="designer-exhibit-flow">
          {sections.map((section) => (
            <div key={section.id} className="designer-section">
              {section.pattern === 'split' ? (
                <div className="designer-row">
                  <article
                    className="designer-case designer-case-large"
                    role="button"
                    tabIndex={0}
                    onClick={handleOpenDetail}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault()
                        handleOpenDetail()
                      }
                    }}
                  >
                    <img src={section.assets[0].image} alt={`${section.assets[0].title}-large`} className="designer-case-image" />
                    <div className="designer-case-meta">
                      <div className="engine">{section.assets[0].engine}</div>
                      <h3>Genesis Node</h3>
                    </div>
                    <div className="designer-loading-bar" />
                  </article>
                  <article
                    className="designer-case designer-case-right"
                    role="button"
                    tabIndex={0}
                    onClick={handleOpenDetail}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault()
                        handleOpenDetail()
                      }
                    }}
                  >
                    <img src={section.assets[1].image} alt={`${section.assets[1].title}-right`} className="designer-case-image grayscale" />
                    <div className="designer-case-meta-right">
                      <div>
                        <p>Archive_Ref</p>
                        <h4>{section.assets[1].title}</h4>
                      </div>
                      <span>#{section.serial}</span>
                    </div>
                    <div className="designer-loading-bar" />
                  </article>
                </div>
              ) : null}

              {section.pattern === 'triple' ? (
                <div className="designer-row designer-row-three">
                  {section.assets.map((asset, idx) => (
                    <article
                      key={`${section.id}-${asset.title}`}
                      className="designer-case designer-case-square"
                      role="button"
                      tabIndex={0}
                      onClick={handleOpenDetail}
                      onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                          event.preventDefault()
                          handleOpenDetail()
                        }
                      }}
                    >
                      <img src={asset.image} alt={`${asset.title}-${idx + 1}`} className="designer-case-image" />
                      <div className="designer-case-square-meta">
                        <span>ID_{section.serial + idx}</span>
                        <span>{asset.title}</span>
                      </div>
                      <div className="designer-loading-bar" />
                    </article>
                  ))}
                </div>
              ) : null}

              {section.pattern === 'hero' ? (
                <div className="designer-row designer-row-hero">
                  <article
                    className="designer-case designer-case-hero"
                    role="button"
                    tabIndex={0}
                    onClick={handleOpenDetail}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault()
                        handleOpenDetail()
                      }
                    }}
                  >
                    <div className="designer-case-hero-meta">
                      <span>Archive Prototype // 2026</span>
                      <h3>{section.assets[0].title}</h3>
                      <p>由 {section.assets[0].engine} 引擎生成的拓扑版本。</p>
                    </div>
                    <img src={section.assets[0].image} alt={`${section.assets[0].title}-hero`} className="designer-case-hero-image" />
                    <div className="designer-loading-bar" />
                  </article>
                </div>
              ) : null}
            </div>
          ))}
        </div>

        <div ref={triggerRef} className="designer-scroll-trigger">
          <div className="designer-trigger-line" />
          <span>Fetching_Cloud_Assets</span>
          <div className="designer-trigger-tip">{isFetching ? '同步設計師數據庫中...' : '滚动继续加载设计档案'}</div>
        </div>
      </main>
    </div>
  )
}

function App() {
  const [page, setPage] = useState<Page>('discover')
  const [detailBackPage, setDetailBackPage] = useState<'discover' | 'design' | 'designer'>('discover')
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [authModalOpen, setAuthModalOpen] = useState(false)
  const [authTab, setAuthTab] = useState<AuthTab>('login')
  const [isAuthConnecting, setIsAuthConnecting] = useState(false)

  useEffect(() => {
    document.body.classList.toggle('workshop-active', page === 'workshop')
    document.body.classList.toggle('factory-active', page === 'factory')
    document.body.classList.toggle('detail-active', page === 'detail')
    document.body.classList.toggle('designer-active', page === 'designer')
    window.scrollTo(0, 0)
    return () => {
      document.body.classList.remove('workshop-active')
      document.body.classList.remove('factory-active')
      document.body.classList.remove('detail-active')
      document.body.classList.remove('designer-active')
    }
  }, [page])

  useEffect(() => {
    document.body.classList.toggle('auth-modal-active', authModalOpen)
    return () => document.body.classList.remove('auth-modal-active')
  }, [authModalOpen])

  const navItems = [
    { key: 'discover', label: '发现', target: 'discover' as const },
    { key: 'design', label: '设计集', target: 'design' as const },
    { key: 'workshop', label: '创作坊', target: 'workshop' as const },
    { key: 'factory', label: '生产间', target: 'factory' as const },
  ]

  const handleMyClick = () => {
    if (isLoggedIn) {
      setPage('my')
      return
    }
    setAuthModalOpen(true)
  }

  const handleSimulateLogin = () => {
    setIsAuthConnecting(true)
    window.setTimeout(() => {
      setIsLoggedIn(true)
      setAuthModalOpen(false)
      setIsAuthConnecting(false)
      setPage('my')
    }, 600)
  }

  const openDetailFrom = (fromPage: 'discover' | 'design' | 'designer') => {
    setDetailBackPage(fromPage)
    setPage('detail')
  }

  return (
    <>
      {page !== 'detail' && page !== 'designer' ? (
        <div className="nav-shell">
          <header className="nav-bar">
            <div className="nav-logo">DAWANG</div>
            <nav className="nav-links" aria-label="primary">
              {navItems.map((item) => (
                <button
                  key={item.key}
                  type="button"
                  className={item.target === page ? 'active' : ''}
                  onClick={() => {
                    if (item.target) {
                      setPage(item.target)
                    }
                  }}
                >
                  {item.label}
                </button>
              ))}
            </nav>
            <div className="nav-right">
              <a
                href="#"
                className={page === 'my' && isLoggedIn ? 'active' : ''}
                onClick={(event) => {
                  event.preventDefault()
                  handleMyClick()
                }}
              >
                我的
              </a>
            </div>
          </header>
        </div>
      ) : null}

      {page === 'discover' ? <DiscoverPage onStartEngine={() => setPage('workshop')} onNavigate={setPage} onOpenDetail={() => openDetailFrom('discover')} /> : null}
      {page === 'design' ? <DesignPage onOpenDetail={() => openDetailFrom('design')} onOpenDesigner={() => setPage('designer')} /> : null}
      {page === 'workshop' ? <WorkshopPage /> : null}
      {page === 'factory' ? <FactoryPage /> : null}
      {page === 'my' && isLoggedIn ? <MyPage onNavigateFactory={() => setPage('factory')} /> : null}
      {page === 'detail' ? <DetailPage onBack={() => setPage(detailBackPage)} /> : null}
      {page === 'designer' ? <DesignerArchivePage onBackToDesign={() => setPage('design')} onOpenDetail={() => openDetailFrom('designer')} /> : null}

      <div className={`auth-modal ${authModalOpen ? 'active' : ''}`}>
        <button type="button" className="auth-bg" onClick={() => setAuthModalOpen(false)} aria-label="Close auth modal background" />

        <div className="auth-modal-stack">
          <button type="button" className="auth-close" onClick={() => setAuthModalOpen(false)} aria-label="Close auth modal">
            ✕
          </button>

          <div className="auth-box">
            <div className="my-bracket my-b-tl auth-bracket" />
            <div className="my-bracket my-b-tr auth-bracket" />

            <div className="auth-header">
              <button type="button" className={`auth-tab ${authTab === 'login' ? 'active' : ''}`} onClick={() => setAuthTab('login')}>
                [ LOGIN ]
              </button>
              <button type="button" className={`auth-tab ${authTab === 'register' ? 'active' : ''}`} onClick={() => setAuthTab('register')}>
                [ REGISTER ]
              </button>
            </div>

            <div className="auth-body">
              <button type="button" className="btn-google" onClick={handleSimulateLogin}>
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                  <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
                  <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
                  <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
                  <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
                </svg>
                Auth via Google
              </button>

              <div className="divider">OR USE PASSKEY</div>

              <div className="input-group">
                <label>Email (信箱地址)</label>
                <input type="email" placeholder="NODE@DAWANG.COM" />
              </div>

              {authTab === 'register' ? (
                <div className="input-group">
                  <label>Verification Code (邮箱验证码)</label>
                  <div className="verify-row">
                    <input type="text" placeholder="6-DIGIT CODE" />
                    <button type="button" className="btn-verify">
                      GET CODE
                    </button>
                  </div>
                </div>
              ) : null}

              <div className="input-group">
                <label>Passkey (访问密钥)</label>
                <input type="password" placeholder="••••••••" />
              </div>

              <button type="button" className="btn-auth" onClick={handleSimulateLogin} disabled={isAuthConnecting}>
                {isAuthConnecting ? '[ CONNECTING... ]' : authTab === 'login' ? 'Initialize Node (登 录)' : 'Register Node (注 册)'}
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                  <line x1="5" y1="12" x2="19" y2="12" />
                  <polyline points="12 5 19 12 12 19" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
