import { useEffect, useRef, useState, type ChangeEvent } from 'react'

type Page = 'discover' | 'design' | 'workshop' | 'factory' | 'my'
type Corner = 'tl' | 'tr' | 'bl' | 'br'
type ArchiveFilter = 'all' | 'studio' | 'community'
type WorkshopMessage = {
  id: number
  type: 'ai' | 'user'
  sender: string
  text: string
}
type FactoryCam = {
  id: string
  label: string
  info: string
  feedText: string
}
type FactoryStep = {
  key: string
  title: string
  text: string
  state: 'done' | 'active' | 'pending'
}
type AuthTab = 'login' | 'register'
type MyOrder = {
  name: string
  id: string
  status: string
  statusType: 'prod' | 'done'
  eta: string
  muted?: boolean
}
type MyMatrixCard = {
  name: string
  status: string
  statusType: 'public' | 'reviewing'
  renderCode: string
  cloned: string
  likes: string
  yield: string
}
type SpotlightCard = {
  key: string
  className: string
  title: string
  center: string
  tag: string
  corners: Corner[]
}

const discoverProjects = [
  {
    id: '01',
    name: 'Aero\nStrata',
    designer: 'Designed by K. YAMAMOTO',
    desc: '基于拓扑优化的极简流体力学骨架，去除冗余结构，整体重量削减 34%。纯粹由算法驱动的物理美学。',
    stamp: '[ FOOTWEAR_RENDER_01 ]',
  },
  {
    id: '02',
    name: 'Bio-Weave\nApex',
    designer: 'Designed by ERROLSON S.',
    desc: '仿生学碳纳米管编织矩阵，全包裹式贴合，动态适应足部受力微血管分布。重塑运动力学的交互边缘。',
    stamp: '[ FOOTWEAR_RENDER_02 ]',
  },
  {
    id: '03',
    name: 'Genesis\nProtocol',
    designer: 'Generated by DAWANG AI',
    desc: '平台首个完全由 AI 自主推演的 100% 碳纤维闭环打印原型，无需任何人工干预即可实现数字到物理的跨越。',
    stamp: '[ FOOTWEAR_RENDER_03 ]',
  },
]

const spotlightCards: SpotlightCard[] = [
  { key: '1', className: 'bp-card-1', title: 'AERO-STRATA 01', center: '[ FULL_SHOE_RENDER ]', tag: 'STATUS: PRODUCTION', corners: ['tl', 'tr', 'bl'] },
  { key: '2', className: 'bp-card-2', title: 'HEEL DETAIL', center: '[ MACRO_SHOT ]', tag: 'CARBON PLATE', corners: ['tl'] },
  { key: '3', className: 'bp-card-3', title: 'V2 ALPHA', center: '[ WIREFRAME ]', tag: '', corners: ['tl', 'br'] },
  { key: '4', className: 'bp-card-4', title: 'MIDSOLE MATRIX', center: '[ FOAM_STRUCTURE_VIEWPORT ]', tag: 'TOPOLOGY_OPT', corners: ['tl', 'tr', 'bl'] },
]

const archiveCards = [
  {
    creator: 'K. Yamamoto',
    badge: 'STUDIO',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=K+Y&background=111&color=fff&font-size=0.4',
    shoe: 'Aero-Strata 01',
    specs: [
      { label: 'Engine', value: 'Topology_Opt' },
      { label: 'Weight', value: '215 G' },
    ],
    code: '[ AERO_RENDER_VIEW ]',
  },
  {
    creator: '@Alex_Design',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=A+D&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Fluid Walker',
    specs: [
      { label: 'Model_Node', value: 'Base_V2.4' },
      { label: 'Gen_Time', value: '14.2 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: 'DAWANG AI',
    badge: 'ENGINE',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=A+I&background=00a8ff&color=fff&font-size=0.4',
    shoe: 'Genesis Protocol',
    specs: [
      { label: 'Engine', value: 'Closed_Loop' },
      { label: 'Weight', value: '205 G' },
    ],
    code: '[ GENESIS_RENDER_VIEW ]',
  },
  {
    creator: '@Neo_99',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=N+9&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Zero Gravity',
    specs: [
      { label: 'Model_Node', value: 'Aero_V1.0' },
      { label: 'Gen_Time', value: '18.1 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: '@Kiko_Fan',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=K+F&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Mech-Boot X',
    specs: [
      { label: 'Model_Node', value: 'Pro_V3.0' },
      { label: 'Gen_Time', value: '21.8 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
]

const workshopShapes = [
  { id: 'low', name: 'Low-Top (低帮)', iconClass: 'ws-shape-low' },
  { id: 'high', name: 'High-Top (高帮)', iconClass: 'ws-shape-high' },
  { id: 'chunky', name: 'Chunky (重装机甲)', iconClass: 'ws-shape-chunky' },
] as const

const workshopSizes = [38, 39, 40, 41, 42, 43]

const factoryQueueItems = [
  'ORDER: #DW-8821 | LOC: TOKYO, JP | PACKAGING',
  'ORDER: #DW-8822 | LOC: BERLIN, DE | ASSEMBLY',
  'ORDER: #DW-8823 | LOC: SHANGHAI, CN | LASER_CUT',
  'ORDER: #DW-8824 | LOC: NEW YORK, US | QA_TESTING',
  'ORDER: #DW-8825 | LOC: LONDON, UK | MATERIAL_PREP',
]

const factoryCameras: FactoryCam[] = [
  {
    id: 'cam-01',
    label: 'CAM_01: CUTTING',
    info: 'CAM_01 // LASER_CUTTING_BAY',
    feedText: '[ SENSOR_STREAM // CUTTING_LINE ]',
  },
  {
    id: 'cam-02',
    label: 'CAM_02: ASSEMBLY',
    info: 'CAM_02 // KUKA_ROBOTIC_ARM',
    feedText: '[ CONNECTING TO FACTORY VISUAL SENSOR... ]',
  },
  {
    id: 'cam-03',
    label: 'CAM_03: QA_LAB',
    info: 'CAM_03 // QA_IMPACT_STATION',
    feedText: '[ CALIBRATING PRESSURE & FLEX TEST RIG... ]',
  },
  {
    id: 'cam-04',
    label: 'CAM_04: PACKAGING',
    info: 'CAM_04 // AUTO_PACKAGING_LINE',
    feedText: '[ TRACKING FINAL PACKAGING & SEALING... ]',
  },
]

const factorySteps: FactoryStep[] = [
  {
    key: '01',
    title: '01. Topology Slicing',
    text: '算法切片完毕，物理模型建立。 (100%)',
    state: 'done',
  },
  {
    key: '02',
    title: '02. Material Prep',
    text: '碳纤维及高分子发泡材料就绪。 (100%)',
    state: 'done',
  },
  {
    key: '03',
    title: '03. Robotic Assembly',
    text: '机械臂正在进行无缝针织与缝合... (In Progress)',
    state: 'active',
  },
  {
    key: '04',
    title: '04. Quality Assurance',
    text: '等待进入压力与抗扭转测试。',
    state: 'pending',
  },
  {
    key: '05',
    title: '05. Ready to Ship',
    text: '封装并生成数字孪生证书。',
    state: 'pending',
  },
]

const myOrders: MyOrder[] = [
  {
    name: 'Aero-Strata Custom',
    id: 'ORDER: #DW-9920X',
    status: 'ROBOTIC_ASSEMBLY',
    statusType: 'prod',
    eta: 'ETA: 14H 22M',
  },
  {
    name: 'Fluid Walker',
    id: 'ORDER: #DW-8841Y',
    status: 'LASER_CUTTING',
    statusType: 'prod',
    eta: 'ETA: 48H 10M',
  },
  {
    name: 'Mech-Boot X',
    id: 'ORDER: #DW-1102A',
    status: 'DELIVERED',
    statusType: 'done',
    eta: '2026.04.10',
    muted: true,
  },
]

const myMatrixCards: MyMatrixCard[] = [
  {
    name: 'Fluid Walker V1',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_01 ]',
    cloned: '142 PAIRS',
    likes: '8,402',
    yield: '¥ 8,650',
  },
  {
    name: 'Neon Glide',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_02 ]',
    cloned: '68 PAIRS',
    likes: '3,120',
    yield: '¥ 3,800',
  },
  {
    name: 'Cyber-Knit 00',
    status: 'REVIEWING',
    statusType: 'reviewing',
    renderCode: '[ RENDER_VIEW_03 ]',
    cloned: '0 PAIRS',
    likes: '12',
    yield: '¥ 0',
  },
]

const formatFactoryTime = (date: Date) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  return `${date.getFullYear()}.${pad(date.getMonth() + 1)}.${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(
    date.getSeconds(),
  )} SYS_TIME`
}

const formatFactoryEta = (seconds: number) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  const safe = Math.max(0, seconds)
  const hours = Math.floor(safe / 3600)
  const minutes = Math.floor((safe % 3600) / 60)
  const secs = safe % 60
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)}`
}

function DiscoverPage({ onStartEngine }: { onStartEngine: () => void }) {
  return (
    <>
      <div className="bg-shape shape1" />

      <section className="hero-container">
        <div className="hero-slogan-wrapper">
          <h1 className="hero-slogan">
            DESIGN THE <span className="highlight">UNSEEN.</span>
          </h1>
        </div>

        <div className="hero-text-block">
          <p className="hero-description">
            接入 DAWANG 工业互联引擎。<br />
            <br />
            上传思维碎片，AI 即刻重构物理鞋身，
            <br />
            72小时内数字孪生至物理现实。
          </p>
        </div>

        <div className="hero-visual-wrapper">
          <div className="hero-visual-placeholder">
            <div className="crosshair tl" />
            <div className="crosshair tr" />
            <div className="crosshair bl" />
            <div className="crosshair br" />
            <span className="cad-text">[ RENDER_VIEWPORT ]</span>
          </div>

          <a
            href="#"
            className="hero-action"
            onClick={(event) => {
              event.preventDefault()
              onStartEngine()
            }}
          >
            <span>前往创作</span>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </a>
        </div>
      </section>

      <section className="editorial-section">
        <header className="section-header">
          <h2 className="section-title">Master Archive.</h2>
          <span className="section-meta">COLLECTION 01</span>
        </header>

        {discoverProjects.map((project) => (
          <article key={project.id} className="project-block">
            <div className="project-visual">
              <span className="placeholder-stamp">{project.stamp}</span>
            </div>
            <div className="project-info">
              <span className="project-number">{project.id} //</span>
              <h3 className="project-name">{project.name}</h3>
              <span className="project-designer">{project.designer}</span>
              <p className="project-desc">{project.desc}</p>
              <a href="#" className="btn-explore" onClick={(event) => event.preventDefault()}>
                Explore Model
              </a>
            </div>
          </article>
        ))}
      </section>
    </>
  )
}

function DesignPage() {
  const [activeFilter, setActiveFilter] = useState<ArchiveFilter>('all')
  const filteredCards = archiveCards.filter((card) => activeFilter === 'all' || card.category === activeFilter)

  return (
    <>
      <section className="spotlight-section">
        <div className="spotlight-header">
          <h2>Daily Spotlight.</h2>
          <span>[ FEATURED DESIGNER ]</span>
        </div>

        <div className="matrix-meta-header">
          <div className="meta-col">
            <span className="label">CREATOR_TYPE</span>
            <span className="value">MASTER_TIER</span>
          </div>
          <div className="meta-col">
            <span className="label">TOTAL_DESIGNS</span>
            <span className="value blue">04 PROTOTYPES</span>
          </div>
          <div className="meta-col">
            <span className="label">STYLE_MATRIX</span>
            <span className="value desc">Aero-Strata 核心系列，极简流体力学。</span>
          </div>
        </div>

        <div className="blueprint-grid">
          {spotlightCards.map((card) => (
            <article key={card.key} className={`bp-card ${card.className}`}>
              {card.corners.includes('tl') ? <div className="bracket b-tl" /> : null}
              {card.corners.includes('tr') ? <div className="bracket b-tr" /> : null}
              {card.corners.includes('bl') ? <div className="bracket b-bl" /> : null}
              {card.corners.includes('br') ? <div className="bracket b-br" /> : null}

              <h3 className="bp-title">{card.title}</h3>
              <span className="bp-center-text">{card.center}</span>
              {card.tag ? <span className="bp-tag">{card.tag}</span> : null}
            </article>
          ))}
        </div>
      </section>

      <header className="archive-header-design">
        <h1 className="page-title">
          The Archive. <span>// PROTOTYPE_DB</span>
        </h1>

        <div className="filter-console">
          <div className="filter-tabs">
            <button type="button" className={`tab-item ${activeFilter === 'all' ? 'active' : ''}`} onClick={() => setActiveFilter('all')}>
              全部档案 (9,204)
            </button>
            <button type="button" className={`tab-item ${activeFilter === 'studio' ? 'active' : ''}`} onClick={() => setActiveFilter('studio')}>
              官方发布 STUDIO
            </button>
            <button type="button" className={`tab-item ${activeFilter === 'community' ? 'active' : ''}`} onClick={() => setActiveFilter('community')}>
              用户共创 COMMUNITY
            </button>
          </div>

          <div className="search-box">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
              <circle cx="11" cy="11" r="8" />
              <line x1="21" y1="21" x2="16.65" y2="16.65" />
            </svg>
            <input type="text" placeholder="搜索鞋款 / 设计师..." />
          </div>
        </div>
      </header>

      <main className="archive-grid-design">
        {filteredCards.map((card) => (
          <article key={card.shoe} className="data-card">
            <div className="card-header">
              <div className="creator-info">
                <div className="creator-avatar">
                  <img src={card.avatar} alt="avatar" />
                </div>
                <span className="creator-name">{card.creator}</span>
              </div>
              <span className={`badge ${card.badgeClass}`}>{card.badge}</span>
            </div>

            <div className="card-visual">
              <div className="floating-brand">DAWANG</div>
              <span className="render-code">{card.code}</span>
            </div>

            <div className="card-footer">
              <h3 className="shoe-name">{card.shoe}</h3>
              <div className="specs-grid">
                {card.specs.map((spec) => (
                  <div key={spec.label} className="spec-item">
                    <span className="label">{spec.label}</span>
                    <span className="val">{spec.value}</span>
                  </div>
                ))}
              </div>
            </div>
          </article>
        ))}
      </main>
    </>
  )
}

function WorkshopPage() {
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const chatLogRef = useRef<HTMLDivElement | null>(null)
  const messageIdRef = useRef(1)
  const [isImageUploaded, setIsImageUploaded] = useState(false)
  const [uploadedImage, setUploadedImage] = useState<string | null>(null)
  const [isAiModalOpen, setIsAiModalOpen] = useState(false)
  const [selectedShape, setSelectedShape] = useState<(typeof workshopShapes)[number]['id']>('low')
  const [selectedSize, setSelectedSize] = useState(40)
  const [aiPrompt, setAiPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [canvasText, setCanvasText] = useState('[ TEXTURE LOADED ]')
  const [canvasGenerated, setCanvasGenerated] = useState(false)
  const [messages, setMessages] = useState<WorkshopMessage[]>([
    {
      id: 1,
      type: 'ai',
      sender: 'DAWANG_AI',
      text: '视觉生成节点已连接。已载入您上传的纹理图，您可以直接输入文字指令进行物理结构的重构（例：“将主材质变更为液态金属感”）。',
    },
  ])

  useEffect(() => {
    if (chatLogRef.current) {
      chatLogRef.current.scrollTop = chatLogRef.current.scrollHeight
    }
  }, [messages])

  useEffect(() => {
    return () => {
      if (uploadedImage?.startsWith('blob:')) {
        URL.revokeObjectURL(uploadedImage)
      }
    }
  }, [uploadedImage])

  const handleViewportClick = () => {
    if (!isImageUploaded) {
      fileInputRef.current?.click()
      return
    }
    setIsAiModalOpen(true)
  }

  const handleFileSelected = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    if (uploadedImage?.startsWith('blob:')) {
      URL.revokeObjectURL(uploadedImage)
    }

    const objectUrl = URL.createObjectURL(file)
    setUploadedImage(objectUrl)
    setIsImageUploaded(true)
    setCanvasText('[ TEXTURE LOADED ]')
    setCanvasGenerated(false)
    event.target.value = ''
  }

  const sendPrompt = () => {
    const text = aiPrompt.trim()
    if (!text) return

    const userMessageId = ++messageIdRef.current
    setMessages((previous) => [...previous, { id: userMessageId, type: 'user', sender: 'CREATOR', text }])
    setAiPrompt('')

    window.setTimeout(() => {
      const loadingMessageId = ++messageIdRef.current
      setMessages((previous) => [
        ...previous,
        { id: loadingMessageId, type: 'ai', sender: 'DAWANG_AI', text: '指令已接收，正在结合源纹理重构三维拓扑... [ 预计耗时 3s ]' },
      ])
      setIsGenerating(true)
      setCanvasText('[ COMPUTING_NEURAL_NODES... ]')
      setCanvasGenerated(false)

      window.setTimeout(() => {
        setMessages((previous) =>
          previous.map((msg) =>
            msg.id === loadingMessageId
              ? { ...msg, text: '渲染重构已完成。您可以继续追加指令进行微调，或关闭面板确认应用。' }
              : msg,
          ),
        )
        setIsGenerating(false)
        setCanvasText('[ NEW_RENDER_APPLIED ]')
        setCanvasGenerated(true)
      }, 3000)
    }, 500)
  }

  return (
    <>
      <main className="workshop-layout">
        <section className="viewport-side">
          <input ref={fileInputRef} type="file" className="hidden-file-input" accept="image/*" onChange={handleFileSelected} />

          <div
            className={`viewport-box ${isImageUploaded ? 'ready' : ''}`}
            onClick={handleViewportClick}
            style={
              uploadedImage
                ? {
                    backgroundImage: `url(${uploadedImage})`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    backgroundColor: 'rgba(255, 255, 255, 0.85)',
                  }
                : undefined
            }
            role="button"
            tabIndex={0}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                handleViewportClick()
              }
            }}
          >
            <div className="viewport-status">{isImageUploaded ? 'AI_READY' : 'AWAITING_TEXTURE'}</div>
            <div className="ws-bracket ws-b-tl" />
            <div className="ws-bracket ws-b-tr" />
            <div className="ws-bracket ws-b-bl" />
            <div className="ws-bracket ws-b-br" />

            {!isImageUploaded ? (
              <div className="upload-ui">
                <div className="upload-icon">+</div>
                <p className="upload-text">[ CLICK TO UPLOAD TEXTURE ]</p>
              </div>
            ) : (
              <div className="viewport-center">[ LAUNCH AI ENGINE ]</div>
            )}

            <div className="viewport-coord">
              X: 0.000
              <br />
              Y: 0.000
              <br />
              Z: 0.000
            </div>
          </div>
        </section>

        <section className="config-side">
          <div className="config-header">
            <h1>Creation Lab.</h1>
            <span>// PARAMETRIC_CONFIGURATOR</span>
          </div>

          <div className="config-step">
            <div className="step-title">01 // Base Geometry (基础鞋型)</div>
            <div className="shape-grid">
              {workshopShapes.map((shape) => (
                <button
                  key={shape.id}
                  type="button"
                  className={`shape-card ${selectedShape === shape.id ? 'active' : ''}`}
                  onClick={() => setSelectedShape(shape.id)}
                >
                  <div className={`shape-icon ${shape.iconClass}`} />
                  <span className="shape-name">{shape.name}</span>
                </button>
              ))}
            </div>
          </div>

          <div className="config-step">
            <div className="step-title">02 // Dimension (物理鞋码)</div>
            <div className="size-grid">
              {workshopSizes.map((size) => (
                <button
                  key={size}
                  type="button"
                  className={`size-btn ${selectedSize === size ? 'active' : ''}`}
                  onClick={() => setSelectedSize(size)}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>
        </section>

        <div className="action-dock">
          <div className="dock-info">
            <span className="price">¥ 1,299.00</span>
            <span className="time">EST. LEAD TIME: 72 HOURS</span>
          </div>
          <button className="btn-submit" type="button">
            Initiate Build
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </button>
        </div>
      </main>

      <div className={`ai-modal ${isAiModalOpen ? 'active' : ''}`}>
        <button type="button" className="ai-modal-bg" onClick={() => setIsAiModalOpen(false)} aria-label="Close AI modal background" />
        <div className="ai-window">
          <button type="button" className="ai-close" onClick={() => setIsAiModalOpen(false)} aria-label="Close AI modal">
            ✕
          </button>

          <div className="ai-left">
            <div className="ai-canvas-header">
              <span>[ AI_VISION_WORKSPACE ]</span>
              <span className="ai-node">NODE: DAWANG_GEN_V4</span>
            </div>
            <div
              className="ai-canvas"
              style={
                uploadedImage
                  ? {
                      backgroundImage: `url(${uploadedImage})`,
                      backgroundColor: 'rgba(255, 255, 255, 0.6)',
                    }
                  : undefined
              }
            >
              {isGenerating ? <div className="scan-line" /> : null}
              <div className={`ai-image-placeholder ${canvasGenerated ? 'generated' : ''}`}>{canvasText}</div>
            </div>
          </div>

          <div className="ai-right">
            <div className="ai-chat-header">
              <h3>AI_RECONSTRUCT</h3>
              <span>// 深度材质与结构重写节点</span>
            </div>
            <div ref={chatLogRef} className="ai-chat-log">
              {messages.map((message) => (
                <div key={message.id} className={`chat-msg ${message.type}`}>
                  <div className="sender">{message.sender}</div>
                  <div className="text">{message.text}</div>
                </div>
              ))}
            </div>
            <div className="ai-input-area">
              <div className="ai-input-wrapper">
                <input
                  type="text"
                  value={aiPrompt}
                  onChange={(event) => setAiPrompt(event.target.value)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter') {
                      event.preventDefault()
                      sendPrompt()
                    }
                  }}
                  placeholder="输入 Prompt 指令进行修改..."
                />
                <button type="button" className="ai-send-btn" onClick={sendPrompt}>
                  SEND
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

function FactoryPage() {
  const [activeCamId, setActiveCamId] = useState(factoryCameras[1].id)
  const [realTime, setRealTime] = useState(() => formatFactoryTime(new Date()))
  const [etaSeconds, setEtaSeconds] = useState(14 * 3600 + 22 * 60 + 5)
  const activeCam = factoryCameras.find((cam) => cam.id === activeCamId) ?? factoryCameras[1]
  const rollingQueue = [...factoryQueueItems, ...factoryQueueItems]

  useEffect(() => {
    const timerId = window.setInterval(() => setRealTime(formatFactoryTime(new Date())), 1000)
    return () => window.clearInterval(timerId)
  }, [])

  useEffect(() => {
    const timerId = window.setInterval(() => setEtaSeconds((prev) => Math.max(0, prev - 1)), 1000)
    return () => window.clearInterval(timerId)
  }, [])

  return (
    <div className="factory-page">
      <header className="factory-dashboard-header">
        <div className="factory-page-title">
          <h1>The Factory.</h1>
        </div>
      </header>

      <div className="factory-global-queue">
        <div className="factory-queue-track">
          {rollingQueue.map((item, index) => {
            const [prefix, orderPart, locPart, statusPart] = item.split('|')
            return (
              <div key={`${item}-${index}`} className="factory-queue-item">
                <span>{prefix.trim()}</span>
                <span className="q-id">{orderPart?.replace('ORDER:', '').trim()}</span>
                <span>{locPart?.trim()}</span>
                <span className="q-status">{statusPart?.trim()}</span>
              </div>
            )
          })}
        </div>
      </div>

      <main className="factory-control-room">
        <section className="factory-live-monitor">
          <div className="factory-video-feed">
            <div className="factory-osd-top-left">
              <div className="factory-live-badge">
                <div className="factory-dot-red" /> LIVE RECORDING
              </div>
              <div className="factory-cam-info">{activeCam.info}</div>
            </div>

            <svg className="factory-crosshair" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <line x1="50%" y1="0" x2="50%" y2="100%" stroke="white" strokeWidth="1" strokeDasharray="5,5" />
              <line x1="0" y1="50%" x2="100%" y2="50%" stroke="white" strokeWidth="1" strokeDasharray="5,5" />
              <circle cx="50%" cy="50%" r="30" fill="none" stroke="white" strokeWidth="1" />
            </svg>

            <div className="factory-video-feed-text">{activeCam.feedText}</div>

            <div className="factory-osd-bottom-right">
              DAWANG ENGINE V1.0.4
              <br />
              <span>{realTime}</span>
            </div>
          </div>

          <div className="factory-cam-switcher">
            {factoryCameras.map((camera) => (
              <button
                key={camera.id}
                type="button"
                className={`factory-cam-btn ${camera.id === activeCam.id ? 'active' : ''}`}
                onClick={() => setActiveCamId(camera.id)}
              >
                {camera.label}
              </button>
            ))}
          </div>
        </section>

        <section className="factory-order-panel">
          <div className="factory-panel-header">
            <h3>My Prototype</h3>
            <span className="factory-order-id">#DW-9920X</span>
          </div>

          <div className="factory-order-content">
            <div className="factory-order-preview">
              <span>[ YOUR_DESIGN_BLUEPRINT ]</span>
            </div>

            <div className="factory-eta-box">
              <div className="label">ESTIMATED TIME TO COMPLETION</div>
              <div className="time">{formatFactoryEta(etaSeconds)}</div>
            </div>

            <div className="factory-tracker">
              {factorySteps.map((step, index) => (
                <div key={step.key} className={`factory-step ${step.state} ${index === factorySteps.length - 1 ? 'last' : ''}`}>
                  <div className="factory-step-icon">{step.state === 'active' ? <div className="factory-inner-dot" /> : null}</div>
                  <div className="factory-step-info">
                    <h4>{step.title}</h4>
                    <p>{step.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function MyPage({ onNavigateFactory }: { onNavigateFactory: () => void }) {
  return (
    <main className="my-dashboard-container">
      <header className="my-profile-header">
        <div className="my-profile-avatar">
          <img src="https://ui-avatars.com/api/?name=A+D&background=f4f4f5&color=111&font-size=0.4" alt="avatar" />
        </div>
        <div className="my-profile-info">
          <h1>@Alex_Design</h1>
          <div className="my-profile-tags">
            <span className="my-tag primary">COMMUNITY_CREATOR</span>
            <span className="my-tag">SYS_NODE_ACTIVE</span>
            <span className="my-tag">JOINED: 2025.10</span>
          </div>
        </div>
      </header>

      <section className="my-top-grid">
        <div className="my-panel my-financial-panel">
          <div className="my-panel-title">
            <strong>Financial Node</strong>
            <span>// 收益终端</span>
          </div>

          <span className="my-fin-subtitle">AVAILABLE YIELD (可提现收益)</span>
          <div className="my-balance-huge">¥ 12,450.00</div>

          <div className="my-fin-stats">
            <div className="my-f-stat">
              <span className="lbl">PENDING SETTLEMENT (待结算)</span>
              <span className="val">¥ 3,200.00</span>
            </div>
            <div className="my-f-stat">
              <span className="lbl">COMMISSION RATE (抽成比)</span>
              <span className="val">15.0%</span>
            </div>
          </div>

          <button type="button" className="my-btn-withdraw">
            Initiate Withdrawal (提取收益)
          </button>
        </div>

        <div className="my-panel">
          <div className="my-panel-title">
            <strong>Production Queue</strong>
            <span>
              <button type="button" className="my-view-factory-link" onClick={onNavigateFactory}>
                VIEW_FACTORY_LIVE -&gt;
              </button>
            </span>
          </div>

          <div className="my-order-list">
            {myOrders.map((order) => (
              <div key={order.id} className={`my-order-item ${order.muted ? 'muted' : ''}`}>
                <div className="my-o-left">
                  <div className="my-o-thumb">
                    <span>[PIC]</span>
                  </div>
                  <div className="my-o-info">
                    <span className="name">{order.name}</span>
                    <span className="id">{order.id}</span>
                  </div>
                </div>
                <div className="my-o-right">
                  <div className="my-status-badge">
                    <div className={`my-dot ${order.statusType}`} />
                    {order.status}
                  </div>
                  <span className="my-o-date">{order.eta}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="my-panel my-matrix-panel">
        <div className="my-panel-title my-panel-title-large">
          <strong>Commission Matrix.</strong>
          <span>// PUBLISHED BLUEPRINTS (已发布开源设计)</span>
        </div>

        <div className="my-matrix-grid">
          {myMatrixCards.map((card) => (
            <div key={card.name} className={`my-matrix-card ${card.statusType === 'reviewing' ? 'reviewing' : ''}`}>
              <div className="my-mc-visual">
                <div className="my-bracket my-b-tl" />
                <div className="my-bracket my-b-tr" />
                <div className="my-bracket my-b-bl" />
                <div className="my-bracket my-b-br" />
                <span className="my-mc-visual-text">{card.renderCode}</span>
              </div>
              <div className="my-mc-data">
                <div className="my-mc-header">
                  <h3 className="my-mc-name">{card.name}</h3>
                  <span className={`my-mc-status ${card.statusType === 'reviewing' ? 'reviewing' : ''}`}>{card.status}</span>
                </div>
                <div className="my-mc-stats">
                  <div className="my-s-item">
                    <span className="lbl">CLONED (被制造)</span>
                    <span className="val">{card.cloned}</span>
                  </div>
                  <div className="my-s-item">
                    <span className="lbl">LIKES (获赞)</span>
                    <span className="val">{card.likes}</span>
                  </div>
                  <div className="my-s-item highlight">
                    <span className="lbl">TOTAL YIELD (总收益)</span>
                    <span className="val">{card.yield}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  )
}

function App() {
  const [page, setPage] = useState<Page>('discover')
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [authModalOpen, setAuthModalOpen] = useState(false)
  const [authTab, setAuthTab] = useState<AuthTab>('login')
  const [isAuthConnecting, setIsAuthConnecting] = useState(false)

  useEffect(() => {
    document.body.classList.toggle('workshop-active', page === 'workshop')
    document.body.classList.toggle('factory-active', page === 'factory')
    return () => {
      document.body.classList.remove('workshop-active')
      document.body.classList.remove('factory-active')
    }
  }, [page])

  useEffect(() => {
    document.body.classList.toggle('auth-modal-active', authModalOpen)
    return () => document.body.classList.remove('auth-modal-active')
  }, [authModalOpen])

  const navItems = [
    { key: 'discover', label: '发现', target: 'discover' as const },
    { key: 'design', label: '设计集', target: 'design' as const },
    { key: 'workshop', label: '创作坊', target: 'workshop' as const },
    { key: 'factory', label: '生产间', target: 'factory' as const },
  ]

  const handleMyClick = () => {
    if (isLoggedIn) {
      setPage('my')
      return
    }
    setAuthModalOpen(true)
  }

  const handleSimulateLogin = () => {
    setIsAuthConnecting(true)
    window.setTimeout(() => {
      setIsLoggedIn(true)
      setAuthModalOpen(false)
      setIsAuthConnecting(false)
      setPage('my')
    }, 600)
  }

  return (
    <>
      <div className="nav-shell">
        <header className="nav-bar">
          <div className="nav-logo">DAWANG</div>
          <nav className="nav-links" aria-label="primary">
            {navItems.map((item) => (
              <button
                key={item.key}
                type="button"
                className={item.target === page ? 'active' : ''}
                onClick={() => {
                  if (item.target) {
                    setPage(item.target)
                  }
                }}
              >
                {item.label}
              </button>
            ))}
          </nav>
          <div className="nav-right">
            <a
              href="#"
              className={page === 'my' && isLoggedIn ? 'active' : ''}
              onClick={(event) => {
                event.preventDefault()
                handleMyClick()
              }}
            >
              我的
            </a>
          </div>
        </header>
      </div>

      {page === 'discover' ? <DiscoverPage onStartEngine={() => setPage('workshop')} /> : null}
      {page === 'design' ? <DesignPage /> : null}
      {page === 'workshop' ? <WorkshopPage /> : null}
      {page === 'factory' ? <FactoryPage /> : null}
      {page === 'my' && isLoggedIn ? <MyPage onNavigateFactory={() => setPage('factory')} /> : null}

      <div className={`auth-modal ${authModalOpen ? 'active' : ''}`}>
        <button type="button" className="auth-bg" onClick={() => setAuthModalOpen(false)} aria-label="Close auth modal background" />

        <div className="auth-modal-stack">
          <button type="button" className="auth-close" onClick={() => setAuthModalOpen(false)} aria-label="Close auth modal">
            ✕
          </button>

          <div className="auth-box">
            <div className="my-bracket my-b-tl auth-bracket" />
            <div className="my-bracket my-b-tr auth-bracket" />

            <div className="auth-header">
              <button type="button" className={`auth-tab ${authTab === 'login' ? 'active' : ''}`} onClick={() => setAuthTab('login')}>
                [ LOGIN ]
              </button>
              <button type="button" className={`auth-tab ${authTab === 'register' ? 'active' : ''}`} onClick={() => setAuthTab('register')}>
                [ REGISTER ]
              </button>
            </div>

            <div className="auth-body">
              <div className="auth-title">{authTab === 'login' ? '// SYS_AUTH_NODE' : '// CREATE_NEW_NODE'}</div>

              <button type="button" className="btn-google" onClick={handleSimulateLogin}>
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                  <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
                  <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
                  <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
                  <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
                </svg>
                Auth via Google
              </button>

              <div className="divider">OR USE PASSKEY</div>

              <div className="input-group">
                <label>Email (信箱地址)</label>
                <input type="email" placeholder="NODE@DAWANG.COM" />
              </div>

              {authTab === 'register' ? (
                <div className="input-group">
                  <label>Verification Code (邮箱验证码)</label>
                  <div className="verify-row">
                    <input type="text" placeholder="6-DIGIT CODE" />
                    <button type="button" className="btn-verify">
                      GET CODE
                    </button>
                  </div>
                </div>
              ) : null}

              <div className="input-group">
                <label>Passkey (访问密钥)</label>
                <input type="password" placeholder="••••••••" />
              </div>

              <button type="button" className="btn-auth" onClick={handleSimulateLogin} disabled={isAuthConnecting}>
                {isAuthConnecting ? '[ CONNECTING... ]' : authTab === 'login' ? 'Initialize Node (登 录)' : 'Register Node (注 册)'}
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                  <line x1="5" y1="12" x2="19" y2="12" />
                  <polyline points="12 5 19 12 12 19" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
