import type { DesignerAsset, DesignerProfile, FactoryCam, FactoryStep, MyMatrixCard, MyOrder, SpotlightCard } from './types'

export const discoverProjects = [
  {
    id: '01',
    name: 'Aero\nStrata',
    designer: 'Designed by K. YAMAMOTO',
    desc: '基于拓扑优化的极简流体力学骨架，去除冗余结构，整体重量削减 34%。纯粹由算法驱动的物理美学。',
    stamp: '[ FOOTWEAR_RENDER_01 ]',
    image:
      'https://plus.unsplash.com/premium_photo-1682125177822-63c27a3830ea?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: '02',
    name: 'Bio-Weave\nApex',
    designer: 'Designed by ERROLSON S.',
    desc: '仿生学碳纳米管编织矩阵，全包裹式贴合，动态适应足部受力微血管分布。重塑运动力学的交互边缘。',
    stamp: '[ FOOTWEAR_RENDER_02 ]',
    image:
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: '03',
    name: 'Genesis\nProtocol',
    designer: 'Generated by DAWANG AI',
    desc: '平台首个完全由 AI 自主推演的 100% 碳纤维闭环打印原型，无需任何人工干预即可实现数字到物理的跨越。',
    stamp: '[ FOOTWEAR_RENDER_03 ]',
    image:
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  },
]

export const discoverHeroImage =
  'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c2hvZXN8ZW58MHx8MHx8fDA%3D'

export const designGalleryImages = [
  'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://plus.unsplash.com/premium_photo-1682125177822-63c27a3830ea?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNob2VzfGVufDB8fDB8fHww',
  'https://images.pexels.com/photos/15632866/pexels-photo-15632866/free-photo-of-close-up-of-shoe.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2hvZXN8ZW58MHx8MHx8fDA%3D',
]

export const getDesignImage = (index: number) => designGalleryImages[index % designGalleryImages.length]

export const designerSeedNodes: DesignerProfile[] = [
  {
    id: 'K_Yamamoto',
    displayName: 'K_Yamamoto',
    node: '0927',
    title: 'K. YAMAMOTO',
    streamNote: '“鞋不是被装饰出来的，而是被结构推导出来的。每一条线都要回答力学与情绪的双重问题。”',
  },
  {
    id: 'Alex_Design',
    displayName: '@Alex_Design',
    node: '1104',
    title: 'ALEX DESIGN',
    streamNote: '“我把城市夜色当作材质，用霓虹与金属切面去表达速度感和不稳定美学。”',
  },
  {
    id: 'Neo_99',
    displayName: '@Neo_99',
    node: '2281',
    title: 'NEO 99',
    streamNote: '“故障不是噪音，而是秩序露出的裂缝。我只负责把它放大给你看。”',
  },
  {
    id: 'Dawang_AI',
    displayName: 'Dawang_AI',
    node: 'CORE',
    title: 'DAWANG AI',
    streamNote: '“我不复制风格，我重组规则。每一次生成，都是对制造边界的一次实验。”',
  },
]

export const designerPoolNodes: DesignerProfile[] = [
  { id: 'Cyber_Kicks', displayName: 'Cyber_Kicks', node: '7721', title: 'CYBER KICKS', streamNote: '“机能不是堆料，是在复杂城市里给身体留出呼吸空间。”' },
  { id: 'Luna_Studio', displayName: 'Luna_Studio', node: '1092', title: 'LUNA STUDIO', streamNote: '“我偏爱柔和光谱，因为未来感不一定锋利，也可以安静。”' },
  { id: 'Void_Labs', displayName: 'Void_Labs', node: '0000', title: 'VOID LABS', streamNote: '“减少一切可有可无，只保留真正让人想再次穿上的理由。”' },
  { id: 'Z_Architect', displayName: 'Z_Architect', node: '4402', title: 'Z ARCHITECT', streamNote: '“我把每双鞋当成建筑，重心、承重、流线都必须先成立。”' },
  { id: 'S_Fujimoto', displayName: 'S_Fujimoto', node: '3312', title: 'S. FUJIMOTO', streamNote: '“好的轮廓应该在远处一眼认出，在近处经得起每个细节。”' },
  { id: 'Matrix_01', displayName: 'Matrix_01', node: '8841', title: 'MATRIX 01', streamNote: '“参数是我的语言，风格只是参数在不同边界条件下的结果。”' },
  { id: 'Aero_Form', displayName: 'Aero_Form', node: '5566', title: 'AERO FORM', streamNote: '“速度感来自气流的方向，而不是表面的图案噪声。”' },
  { id: 'Carbon_Pro', displayName: 'Carbon_Pro', node: '3122', title: 'CARBON PRO', streamNote: '“我追求的是轻量与强度的平衡，不是单一维度的极限。”' },
]

export const designerAssetPool: DesignerAsset[] = [
  { title: 'Aero Strata', image: getDesignImage(0), engine: 'GENESIS_V3' },
  { title: 'Magma Kinetic', image: getDesignImage(1), engine: 'FLUX_NODE' },
  { title: 'Void Protocol', image: getDesignImage(2), engine: 'ZERO_GRAV' },
  { title: 'Neon Runner', image: getDesignImage(3), engine: 'URBAN_CORE' },
  { title: 'Topology Gen', image: getDesignImage(4), engine: 'ALPHA_MESH' },
  { title: 'Flux Frame', image: getDesignImage(5), engine: 'DELTA_PRO' },
  { title: 'Hyper Foam', image: getDesignImage(6), engine: 'VECTOR_CLOUD' },
  { title: 'Ion Drift', image: getDesignImage(7), engine: 'DYNAMIC_MAP' },
]

export const designerNodeBatchSize = 2
export const initialDesignerVisibleCount = 10

export const hashValue = (value: string) => {
  let hash = 0
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(i)
    hash |= 0
  }
  return Math.abs(hash)
}

export const pickDesignerAsset = (designerId: string, phase: number, offset: number) => {
  const idx = (hashValue(`${designerId}-${phase}-${offset}`) + phase * 11 + offset * 7) % designerAssetPool.length
  return designerAssetPool[idx]
}

export const spotlightCards: SpotlightCard[] = [
  { key: '1', className: 'bp-card-1', title: 'AERO-STRATA 01', center: '[ FULL_SHOE_RENDER ]', tag: 'STATUS: PRODUCTION', corners: ['tl', 'tr', 'bl'] },
  { key: '2', className: 'bp-card-2', title: 'HEEL DETAIL', center: '[ MACRO_SHOT ]', tag: 'CARBON PLATE', corners: ['tl'] },
  { key: '3', className: 'bp-card-3', title: 'V2 ALPHA', center: '[ WIREFRAME ]', tag: '', corners: ['tl', 'br'] },
  { key: '4', className: 'bp-card-4', title: 'MIDSOLE MATRIX', center: '[ FOAM_STRUCTURE_VIEWPORT ]', tag: 'TOPOLOGY_OPT', corners: ['tl', 'tr', 'bl'] },
]

export const archiveCards = [
  {
    creator: 'K. Yamamoto',
    badge: 'STUDIO',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=K+Y&background=111&color=fff&font-size=0.4',
    shoe: 'Aero-Strata 01',
    specs: [
      { label: 'Engine', value: 'Topology_Opt' },
      { label: 'Weight', value: '215 G' },
    ],
    code: '[ AERO_RENDER_VIEW ]',
  },
  {
    creator: '@Alex_Design',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=A+D&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Fluid Walker',
    specs: [
      { label: 'Model_Node', value: 'Base_V2.4' },
      { label: 'Gen_Time', value: '14.2 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: 'DAWANG AI',
    badge: 'ENGINE',
    badgeClass: 'master',
    category: 'studio',
    avatar: 'https://ui-avatars.com/api/?name=A+I&background=00a8ff&color=fff&font-size=0.4',
    shoe: 'Genesis Protocol',
    specs: [
      { label: 'Engine', value: 'Closed_Loop' },
      { label: 'Weight', value: '205 G' },
    ],
    code: '[ GENESIS_RENDER_VIEW ]',
  },
  {
    creator: '@Neo_99',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=N+9&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Zero Gravity',
    specs: [
      { label: 'Model_Node', value: 'Aero_V1.0' },
      { label: 'Gen_Time', value: '18.1 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
  {
    creator: '@Kiko_Fan',
    badge: 'COMMUNITY',
    badgeClass: 'community',
    category: 'community',
    avatar: 'https://ui-avatars.com/api/?name=K+F&background=f4f4f5&color=111&font-size=0.4',
    shoe: 'Mech-Boot X',
    specs: [
      { label: 'Model_Node', value: 'Pro_V3.0' },
      { label: 'Gen_Time', value: '21.8 S' },
    ],
    code: '[ USER_RENDER_VIEW ]',
  },
]

export const workshopShapes = [
  { id: 'low', name: 'LOW TOP', iconClass: 'shape-low' },
  { id: 'mid', name: 'MID CUT', iconClass: 'shape-mid' },
  { id: 'high', name: 'HIGH TOP', iconClass: 'shape-high' },
  { id: 'runner', name: 'RUNNER', iconClass: 'shape-runner' },
] as const

export const workshopSizes = [38, 39, 40, 41, 42, 43]

export const factoryQueueItems = [
  'QUEUE|ORDER: DW-9920X|LOC: SHENZHEN_F3|STATUS: PRINTING',
  'QUEUE|ORDER: DW-9919C|LOC: DONGGUAN_A2|STATUS: UV COATING',
  'QUEUE|ORDER: DW-9918B|LOC: HANGZHOU_HQ|STATUS: PACKAGING',
  'QUEUE|ORDER: DW-9917K|LOC: SHENZHEN_F3|STATUS: QC CHECK',
]

export const factoryCameras: FactoryCam[] = [
  {
    id: 'cam-a',
    label: 'CAM_A',
    info: 'NODE A // MIDSOLE FABRICATION',
    feedText: 'LIVE FEED // MIDSOLE FABRICATION // PRESSURE 4.9 BAR',
  },
  {
    id: 'cam-b',
    label: 'CAM_B',
    info: 'NODE B // UPPER WEAVE MATRIX',
    feedText: 'LIVE FEED // UPPER WEAVE MATRIX // TENSION 87%',
  },
  {
    id: 'cam-c',
    label: 'CAM_C',
    info: 'NODE C // FINAL ASSEMBLY BAY',
    feedText: 'LIVE FEED // FINAL ASSEMBLY BAY // SYNC LOCKED',
  },
  {
    id: 'cam-d',
    label: 'CAM_D',
    info: 'NODE D // QUALITY INSPECTION',
    feedText: 'LIVE FEED // QUALITY INSPECTION // PASS RATE 99.3%',
  },
]

export const factorySteps: FactoryStep[] = [
  {
    key: 'mesh',
    title: 'Mesh Generation Complete',
    text: '系统已完成三维拓扑结构编译。',
    state: 'done',
  },
  {
    key: 'print',
    title: 'Carbon Midsole Printing',
    text: '当前正在执行碳纤中底打印工序。',
    state: 'active',
  },
  {
    key: 'weave',
    title: 'Upper Weave Fusion',
    text: '待执行鞋面编织熔接工序。',
    state: 'pending',
  },
  {
    key: 'quality',
    title: 'AI Quality Scan',
    text: '待执行 AI 自动质检。',
    state: 'pending',
  },
]

export const myOrders: MyOrder[] = [
  {
    name: 'Aero-Strata 01',
    id: '#DW-9920X',
    status: 'IN_PRODUCTION',
    statusType: 'prod',
    eta: 'ETA: 14h 22m',
  },
  {
    name: 'Flux Runner V2',
    id: '#DW-9861C',
    status: 'COMPLETED',
    statusType: 'done',
    eta: 'DELIVERED: 2 days ago',
    muted: true,
  },
]

export const myMatrixCards: MyMatrixCard[] = [
  {
    name: 'Fluid Walker V1',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_01 ]',
    cloned: '142 PAIRS',
    likes: '8,402',
    yield: '¥ 8,650',
  },
  {
    name: 'Neon Glide',
    status: 'PUBLIC',
    statusType: 'public',
    renderCode: '[ RENDER_VIEW_02 ]',
    cloned: '68 PAIRS',
    likes: '3,120',
    yield: '¥ 3,800',
  },
  {
    name: 'Cyber-Knit 00',
    status: 'REVIEWING',
    statusType: 'reviewing',
    renderCode: '[ RENDER_VIEW_03 ]',
    cloned: '0 PAIRS',
    likes: '12',
    yield: '¥ 0',
  },
]

export const formatFactoryTime = (date: Date) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  return `${date.getFullYear()}.${pad(date.getMonth() + 1)}.${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(
    date.getSeconds(),
  )} SYS_TIME`
}

export const formatFactoryEta = (seconds: number) => {
  const pad = (value: number) => String(value).padStart(2, '0')
  const safe = Math.max(0, seconds)
  const hours = Math.floor(safe / 3600)
  const minutes = Math.floor((safe % 3600) / 60)
  const secs = safe % 60
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)}`
}
